package main

import (
	"fmt"
	"os"
	"os/exec"
	"time"
	"math/rand"

	"bufio"
	"io"
	"strings"
)

var _ os.File
var _ exec.Cmd
var _ = time.Second

func CheckError(err error) { if nil != err { fmt.Printf("err: %v\n", err); panic(err) } }

func FileExists(name string) bool {
	_, err := os.Stat(name)
	return nil == err
}

func GenerateMainFunc() string {
	if 0 == rand.Int63n(10) {
		return `println("Hi")`
	}
	return `print_ln("Hi")`
}

var alphabet = map[string]float64 {
	";": 10.0,
	"\n": 10.0,
	" ": 5.0,
	"print": 10.0,
	"println": 10.0,
	"(": 10.0,
	")": 10.0,
	"\"": 10.0,
	":": 10.0,
	",": 10.0,
	"{": 10.0,
	"}": 10.0,
	"[": 10.0,
	"]": 10.0,
	"_": 10.0,
	"+": 10.0,
	"-": 10.0,
	"*": 10.0,
	"/": 1.0,
	"\\": 10.0,
	"&&": 10.0,
	"||": 10.0,
	"&": 10.0,
	"|": 10.0,

	"a": 1.0,
	"b": 1.0,
	"c": 1.0,
	"d": 1.0,
	"e": 1.0,
	"f": 1.0,
	"g": 1.0,
	"h": 1.0,
	"i": 1.0,
	"j": 1.0,
	"k": 1.0,
	"l": 1.0,
	"m": 1.0,
	"n": 1.0,
	"o": 1.0,
	"p": 1.0,
	"q": 1.0,
	"r": 1.0,
	"s": 1.0,
	"t": 1.0,
	"u": 1.0,
	"v": 1.0,
	"w": 1.0,
	"x": 1.0,
	"y": 1.0,
	"z": 1.0,

	"A": 1.0,
	"B": 1.0,
	"C": 1.0,
	"D": 1.0,
	"E": 1.0,
	"F": 1.0,
	"G": 1.0,
	"H": 1.0,
	"I": 1.0,
	"J": 1.0,
	"K": 1.0,
	"L": 1.0,
	"M": 1.0,
	"N": 1.0,
	"O": 1.0,
	"P": 1.0,
	"Q": 1.0,
	"R": 1.0,
	"S": 1.0,
	"T": 1.0,
	"U": 1.0,
	"V": 1.0,
	"W": 1.0,
	"X": 1.0,
	"Y": 1.0,
	"Z": 1.0,

	"0": 1.0,
	"1": 1.0,
	"2": 1.0,
	"3": 1.0,
	"4": 1.0,
	"5": 1.0,
	"6": 1.0,
	"7": 1.0,
	"8": 1.0,
	"9": 1.0,
}
var totalProb float64

func GenerateMainFunc2() string {
	o := ""
	for i := 0; i < 4 + rand.Int() % 20; i++ {
		r := rand.Float64() * totalProb
		for k, v := range alphabet {
			if r < v {
				o += k
				break
			} else {
				r -= v
			}
		}
	}
	return o
}

// Prefix is a Markov chain prefix of one or more words.
type Prefix []string

// String returns the Prefix as a string (for use as a map key).
func (p Prefix) String() string {
	return strings.Join(p, "")
}

// Shift removes the first word from the Prefix and appends the given word.
func (p Prefix) Shift(word string) {
	copy(p, p[1:])
	p[len(p)-1] = word
}

// Chain contains a map ("chain") of prefixes to a list of suffixes.
// A prefix is a string of prefixLen words joined with spaces.
// A suffix is a single word. A prefix can have multiple suffixes.
type Chain struct {
	chain     map[string][]string
	prefixLen int
}

// NewChain returns a new Chain with prefixes of prefixLen words.
func NewChain(prefixLen int) *Chain {
	return &Chain{make(map[string][]string), prefixLen}
}

// Build reads text from the provided Reader and
// parses it into prefixes and suffixes that are stored in Chain.
func (c *Chain) Build(r io.Reader) {
	br := bufio.NewReader(r)
	p := make(Prefix, c.prefixLen)
	for {
		var s string
		if ru, size, err := br.ReadRune(); err != nil || size != 1 {
			break
		} else {
			s = string(ru)
		}
		key := p.String()
		c.chain[key] = append(c.chain[key], s)
		p.Shift(s)
	}
}

// Generate returns a string of at most n words generated from Chain.
func (c *Chain) Generate(n int) string {
TRY_AGAIN:
	p := make(Prefix, c.prefixLen)
	//p[len(p)-4] = " "
	//p[len(p)-3] = "{"
	p[len(p)-2] = "\n"
	p[len(p)-1] = "\t"
	var words []string
	for {
		choices := c.chain[p.String()]
		if len(choices) == 0 {
			break
		}
		next := choices[rand.Intn(len(choices))]
		words = append(words, next)
		p.Shift(next)
		if len(words) >= 10 && rand.Intn(n) == 0 {
			break
		}
	}
	out := strings.Join(words, "")
	if len(strings.TrimSpace(out)) == 0 {
		goto TRY_AGAIN
	}
	return out
}

var filenames = []string{"/Users/Dmitri/Dmitri/^Work/^GitHub/Conception/Gen/5086673/gistfile1.go",
"/usr/local/go/src/pkg/archive/tar/common.go",
"/usr/local/go/src/pkg/archive/tar/reader.go",
"/usr/local/go/src/pkg/archive/tar/reader_test.go",
"/usr/local/go/src/pkg/archive/tar/writer.go",
"/usr/local/go/src/pkg/archive/tar/writer_test.go",
"/usr/local/go/src/pkg/archive/zip/example_test.go",
"/usr/local/go/src/pkg/archive/zip/reader.go",
"/usr/local/go/src/pkg/archive/zip/reader_test.go",
"/usr/local/go/src/pkg/archive/zip/struct.go",
"/usr/local/go/src/pkg/archive/zip/writer.go",
"/usr/local/go/src/pkg/archive/zip/writer_test.go",
"/usr/local/go/src/pkg/archive/zip/zip_test.go",
"/usr/local/go/src/pkg/bufio/bufio.go",
"/usr/local/go/src/pkg/bufio/bufio_test.go",
"/usr/local/go/src/pkg/builtin/builtin.go",
"/usr/local/go/src/pkg/bytes/buffer.go",
"/usr/local/go/src/pkg/bytes/buffer_test.go",
"/usr/local/go/src/pkg/bytes/bytes.go",
"/usr/local/go/src/pkg/bytes/bytes_decl.go",
"/usr/local/go/src/pkg/bytes/bytes_test.go",
"/usr/local/go/src/pkg/bytes/example_test.go",
"/usr/local/go/src/pkg/bytes/export_test.go",
"/usr/local/go/src/pkg/bytes/reader.go",
"/usr/local/go/src/pkg/bytes/reader_test.go",
"/usr/local/go/src/pkg/compress/bzip2/bit_reader.go",
"/usr/local/go/src/pkg/compress/bzip2/bzip2.go",
"/usr/local/go/src/pkg/compress/bzip2/bzip2_test.go",
"/usr/local/go/src/pkg/compress/bzip2/huffman.go",
"/usr/local/go/src/pkg/compress/bzip2/move_to_front.go",
"/usr/local/go/src/pkg/compress/flate/deflate.go",
"/usr/local/go/src/pkg/compress/flate/deflate_test.go",
"/usr/local/go/src/pkg/compress/flate/flate_test.go",
"/usr/local/go/src/pkg/compress/flate/huffman_bit_writer.go",
"/usr/local/go/src/pkg/compress/flate/huffman_code.go",
"/usr/local/go/src/pkg/compress/flate/inflate.go",
"/usr/local/go/src/pkg/compress/flate/reader_test.go",
"/usr/local/go/src/pkg/compress/flate/reverse_bits.go",
"/usr/local/go/src/pkg/compress/flate/token.go",
"/usr/local/go/src/pkg/compress/gzip/gunzip.go",
"/usr/local/go/src/pkg/compress/gzip/gunzip_test.go",
"/usr/local/go/src/pkg/compress/gzip/gzip.go",
"/usr/local/go/src/pkg/compress/gzip/gzip_test.go",
"/usr/local/go/src/pkg/compress/lzw/reader.go",
"/usr/local/go/src/pkg/compress/lzw/reader_test.go",
"/usr/local/go/src/pkg/compress/lzw/writer.go",
"/usr/local/go/src/pkg/compress/lzw/writer_test.go",
"/usr/local/go/src/pkg/compress/zlib/reader.go",
"/usr/local/go/src/pkg/compress/zlib/reader_test.go",
"/usr/local/go/src/pkg/compress/zlib/writer.go",
"/usr/local/go/src/pkg/compress/zlib/writer_test.go",
"/usr/local/go/src/pkg/container/heap/example_test.go",
"/usr/local/go/src/pkg/container/heap/heap.go",
"/usr/local/go/src/pkg/container/heap/heap_test.go",
"/usr/local/go/src/pkg/container/list/list.go",
"/usr/local/go/src/pkg/container/list/list_test.go",
"/usr/local/go/src/pkg/container/ring/ring.go",
"/usr/local/go/src/pkg/container/ring/ring_test.go",
"/usr/local/go/src/pkg/crypto/aes/aes_test.go",
"/usr/local/go/src/pkg/crypto/aes/block.go",
"/usr/local/go/src/pkg/crypto/aes/cipher.go",
"/usr/local/go/src/pkg/crypto/aes/const.go",
"/usr/local/go/src/pkg/crypto/cipher/cbc.go",
"/usr/local/go/src/pkg/crypto/cipher/cbc_aes_test.go",
"/usr/local/go/src/pkg/crypto/cipher/cfb.go",
"/usr/local/go/src/pkg/crypto/cipher/cfb_test.go",
"/usr/local/go/src/pkg/crypto/cipher/cipher.go",
"/usr/local/go/src/pkg/crypto/cipher/common_test.go",
"/usr/local/go/src/pkg/crypto/cipher/ctr.go",
"/usr/local/go/src/pkg/crypto/cipher/ctr_aes_test.go",
"/usr/local/go/src/pkg/crypto/cipher/io.go",
"/usr/local/go/src/pkg/crypto/cipher/ofb.go",
"/usr/local/go/src/pkg/crypto/cipher/ofb_test.go",
"/usr/local/go/src/pkg/crypto/crypto.go",
"/usr/local/go/src/pkg/crypto/des/block.go",
"/usr/local/go/src/pkg/crypto/des/cipher.go",
"/usr/local/go/src/pkg/crypto/des/const.go",
"/usr/local/go/src/pkg/crypto/des/des_test.go",
"/usr/local/go/src/pkg/crypto/dsa/dsa.go",
"/usr/local/go/src/pkg/crypto/dsa/dsa_test.go",
"/usr/local/go/src/pkg/crypto/ecdsa/ecdsa.go",
"/usr/local/go/src/pkg/crypto/ecdsa/ecdsa_test.go",
"/usr/local/go/src/pkg/crypto/elliptic/elliptic.go",
"/usr/local/go/src/pkg/crypto/elliptic/elliptic_test.go",
"/usr/local/go/src/pkg/crypto/elliptic/p224.go",
"/usr/local/go/src/pkg/crypto/elliptic/p224_test.go",
"/usr/local/go/src/pkg/crypto/hmac/hmac.go",
"/usr/local/go/src/pkg/crypto/hmac/hmac_test.go",
"/usr/local/go/src/pkg/crypto/md5/md5.go",
"/usr/local/go/src/pkg/crypto/md5/md5_test.go",
"/usr/local/go/src/pkg/crypto/md5/md5block.go",
"/usr/local/go/src/pkg/crypto/rand/example_test.go",
"/usr/local/go/src/pkg/crypto/rand/rand.go",
"/usr/local/go/src/pkg/crypto/rand/rand_test.go",
"/usr/local/go/src/pkg/crypto/rand/rand_unix.go",
"/usr/local/go/src/pkg/crypto/rand/rand_windows.go",
"/usr/local/go/src/pkg/crypto/rand/util.go",
"/usr/local/go/src/pkg/crypto/rc4/rc4.go",
"/usr/local/go/src/pkg/crypto/rc4/rc4_test.go",
"/usr/local/go/src/pkg/crypto/rsa/pkcs1v15.go",
"/usr/local/go/src/pkg/crypto/rsa/pkcs1v15_test.go",
"/usr/local/go/src/pkg/crypto/rsa/rsa.go",
"/usr/local/go/src/pkg/crypto/rsa/rsa_test.go",
"/usr/local/go/src/pkg/crypto/sha1/sha1.go",
"/usr/local/go/src/pkg/crypto/sha1/sha1_test.go",
"/usr/local/go/src/pkg/crypto/sha1/sha1block.go",
"/usr/local/go/src/pkg/crypto/sha256/sha256.go",
"/usr/local/go/src/pkg/crypto/sha256/sha256_test.go",
"/usr/local/go/src/pkg/crypto/sha256/sha256block.go",
"/usr/local/go/src/pkg/crypto/sha512/sha512.go",
"/usr/local/go/src/pkg/crypto/sha512/sha512_test.go",
"/usr/local/go/src/pkg/crypto/sha512/sha512block.go",
"/usr/local/go/src/pkg/crypto/subtle/constant_time.go",
"/usr/local/go/src/pkg/crypto/subtle/constant_time_test.go",
"/usr/local/go/src/pkg/crypto/tls/alert.go",
"/usr/local/go/src/pkg/crypto/tls/cipher_suites.go",
"/usr/local/go/src/pkg/crypto/tls/common.go",
"/usr/local/go/src/pkg/crypto/tls/conn.go",
"/usr/local/go/src/pkg/crypto/tls/conn_test.go",
"/usr/local/go/src/pkg/crypto/tls/generate_cert.go",
"/usr/local/go/src/pkg/crypto/tls/handshake_client.go",
"/usr/local/go/src/pkg/crypto/tls/handshake_client_test.go",
"/usr/local/go/src/pkg/crypto/tls/handshake_messages.go",
"/usr/local/go/src/pkg/crypto/tls/handshake_messages_test.go",
"/usr/local/go/src/pkg/crypto/tls/handshake_server.go",
"/usr/local/go/src/pkg/crypto/tls/handshake_server_test.go",
"/usr/local/go/src/pkg/crypto/tls/key_agreement.go",
"/usr/local/go/src/pkg/crypto/tls/prf.go",
"/usr/local/go/src/pkg/crypto/tls/prf_test.go",
"/usr/local/go/src/pkg/crypto/tls/root_test.go",
"/usr/local/go/src/pkg/crypto/tls/tls.go",
"/usr/local/go/src/pkg/crypto/x509/cert_pool.go",
"/usr/local/go/src/pkg/crypto/x509/pkcs1.go",
"/usr/local/go/src/pkg/crypto/x509/pkcs8.go",
"/usr/local/go/src/pkg/crypto/x509/pkcs8_test.go",
"/usr/local/go/src/pkg/crypto/x509/pkix/pkix.go",
"/usr/local/go/src/pkg/crypto/x509/root.go",
"/usr/local/go/src/pkg/crypto/x509/root_darwin.go",
"/usr/local/go/src/pkg/crypto/x509/root_stub.go",
"/usr/local/go/src/pkg/crypto/x509/root_unix.go",
"/usr/local/go/src/pkg/crypto/x509/root_windows.go",
"/usr/local/go/src/pkg/crypto/x509/verify.go",
"/usr/local/go/src/pkg/crypto/x509/verify_test.go",
"/usr/local/go/src/pkg/crypto/x509/x509.go",
"/usr/local/go/src/pkg/crypto/x509/x509_test.go",
"/usr/local/go/src/pkg/database/sql/convert.go",
"/usr/local/go/src/pkg/database/sql/convert_test.go",
"/usr/local/go/src/pkg/database/sql/driver/driver.go",
"/usr/local/go/src/pkg/database/sql/driver/types.go",
"/usr/local/go/src/pkg/database/sql/driver/types_test.go",
"/usr/local/go/src/pkg/database/sql/fakedb_test.go",
"/usr/local/go/src/pkg/database/sql/sql.go",
"/usr/local/go/src/pkg/database/sql/sql_test.go",
"/usr/local/go/src/pkg/debug/dwarf/buf.go",
"/usr/local/go/src/pkg/debug/dwarf/const.go",
"/usr/local/go/src/pkg/debug/dwarf/entry.go",
"/usr/local/go/src/pkg/debug/dwarf/open.go",
"/usr/local/go/src/pkg/debug/dwarf/type.go",
"/usr/local/go/src/pkg/debug/dwarf/type_test.go",
"/usr/local/go/src/pkg/debug/dwarf/unit.go",
"/usr/local/go/src/pkg/debug/elf/elf.go",
"/usr/local/go/src/pkg/debug/elf/elf_test.go",
"/usr/local/go/src/pkg/debug/elf/file.go",
"/usr/local/go/src/pkg/debug/elf/file_test.go",
"/usr/local/go/src/pkg/debug/gosym/pclntab.go",
"/usr/local/go/src/pkg/debug/gosym/pclntab_test.go",
"/usr/local/go/src/pkg/debug/gosym/symtab.go",
"/usr/local/go/src/pkg/debug/macho/file.go",
"/usr/local/go/src/pkg/debug/macho/file_test.go",
"/usr/local/go/src/pkg/debug/macho/macho.go",
"/usr/local/go/src/pkg/debug/pe/file.go",
"/usr/local/go/src/pkg/debug/pe/file_test.go",
"/usr/local/go/src/pkg/debug/pe/pe.go",
"/usr/local/go/src/pkg/encoding/ascii85/ascii85.go",
"/usr/local/go/src/pkg/encoding/ascii85/ascii85_test.go",
"/usr/local/go/src/pkg/encoding/asn1/asn1.go",
"/usr/local/go/src/pkg/encoding/asn1/asn1_test.go",
"/usr/local/go/src/pkg/encoding/asn1/common.go",
"/usr/local/go/src/pkg/encoding/asn1/marshal.go",
"/usr/local/go/src/pkg/encoding/asn1/marshal_test.go",
"/usr/local/go/src/pkg/encoding/base32/base32.go",
"/usr/local/go/src/pkg/encoding/base32/base32_test.go",
"/usr/local/go/src/pkg/encoding/base64/base64.go",
"/usr/local/go/src/pkg/encoding/base64/base64_test.go",
"/usr/local/go/src/pkg/encoding/binary/binary.go",
"/usr/local/go/src/pkg/encoding/binary/binary_test.go",
"/usr/local/go/src/pkg/encoding/binary/example_test.go",
"/usr/local/go/src/pkg/encoding/binary/varint.go",
"/usr/local/go/src/pkg/encoding/binary/varint_test.go",
"/usr/local/go/src/pkg/encoding/csv/reader.go",
"/usr/local/go/src/pkg/encoding/csv/reader_test.go",
"/usr/local/go/src/pkg/encoding/csv/writer.go",
"/usr/local/go/src/pkg/encoding/csv/writer_test.go",
"/usr/local/go/src/pkg/encoding/gob/codec_test.go",
"/usr/local/go/src/pkg/encoding/gob/debug.go",
"/usr/local/go/src/pkg/encoding/gob/decode.go",
"/usr/local/go/src/pkg/encoding/gob/decoder.go",
"/usr/local/go/src/pkg/encoding/gob/doc.go",
"/usr/local/go/src/pkg/encoding/gob/dump.go",
"/usr/local/go/src/pkg/encoding/gob/encode.go",
"/usr/local/go/src/pkg/encoding/gob/encoder.go",
"/usr/local/go/src/pkg/encoding/gob/encoder_test.go",
"/usr/local/go/src/pkg/encoding/gob/error.go",
"/usr/local/go/src/pkg/encoding/gob/gobencdec_test.go",
"/usr/local/go/src/pkg/encoding/gob/timing_test.go",
"/usr/local/go/src/pkg/encoding/gob/type.go",
"/usr/local/go/src/pkg/encoding/gob/type_test.go",
"/usr/local/go/src/pkg/encoding/hex/hex.go",
"/usr/local/go/src/pkg/encoding/hex/hex_test.go",
"/usr/local/go/src/pkg/encoding/json/bench_test.go",
"/usr/local/go/src/pkg/encoding/json/decode.go",
"/usr/local/go/src/pkg/encoding/json/decode_test.go",
"/usr/local/go/src/pkg/encoding/json/encode.go",
"/usr/local/go/src/pkg/encoding/json/encode_test.go",
"/usr/local/go/src/pkg/encoding/json/example_test.go",
"/usr/local/go/src/pkg/encoding/json/indent.go",
"/usr/local/go/src/pkg/encoding/json/scanner.go",
"/usr/local/go/src/pkg/encoding/json/scanner_test.go",
"/usr/local/go/src/pkg/encoding/json/stream.go",
"/usr/local/go/src/pkg/encoding/json/stream_test.go",
"/usr/local/go/src/pkg/encoding/json/tagkey_test.go",
"/usr/local/go/src/pkg/encoding/json/tags.go",
"/usr/local/go/src/pkg/encoding/json/tags_test.go",
"/usr/local/go/src/pkg/encoding/pem/pem.go",
"/usr/local/go/src/pkg/encoding/pem/pem_test.go",
"/usr/local/go/src/pkg/encoding/xml/atom_test.go",
"/usr/local/go/src/pkg/encoding/xml/example_test.go",
"/usr/local/go/src/pkg/encoding/xml/marshal.go",
"/usr/local/go/src/pkg/encoding/xml/marshal_test.go",
"/usr/local/go/src/pkg/encoding/xml/read.go",
"/usr/local/go/src/pkg/encoding/xml/read_test.go",
"/usr/local/go/src/pkg/encoding/xml/typeinfo.go",
"/usr/local/go/src/pkg/encoding/xml/xml.go",
"/usr/local/go/src/pkg/encoding/xml/xml_test.go",
"/usr/local/go/src/pkg/errors/errors.go",
"/usr/local/go/src/pkg/errors/errors_test.go",
"/usr/local/go/src/pkg/errors/example_test.go",
"/usr/local/go/src/pkg/expvar/expvar.go",
"/usr/local/go/src/pkg/expvar/expvar_test.go",
"/usr/local/go/src/pkg/flag/example_test.go",
"/usr/local/go/src/pkg/flag/export_test.go",
"/usr/local/go/src/pkg/flag/flag.go",
"/usr/local/go/src/pkg/flag/flag_test.go",
"/usr/local/go/src/pkg/fmt/doc.go",
"/usr/local/go/src/pkg/fmt/export_test.go",
"/usr/local/go/src/pkg/fmt/fmt_test.go",
"/usr/local/go/src/pkg/fmt/format.go",
"/usr/local/go/src/pkg/fmt/print.go",
"/usr/local/go/src/pkg/fmt/scan.go",
"/usr/local/go/src/pkg/fmt/scan_test.go",
"/usr/local/go/src/pkg/fmt/stringer_test.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/common.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/common_test.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/config.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/doc.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/dump.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/dump_test.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/example_test.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/format.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/format_test.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/internal_test.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/spew.go",
"/usr/local/go/src/pkg/github.com/davecgh/go-spew/spew/spew_test.go",
"/usr/local/go/src/pkg/github.com/howeyc/fsnotify/example_test.go",
"/usr/local/go/src/pkg/github.com/howeyc/fsnotify/fsnotify.go",
"/usr/local/go/src/pkg/github.com/howeyc/fsnotify/fsnotify_bsd.go",
"/usr/local/go/src/pkg/github.com/howeyc/fsnotify/fsnotify_linux.go",
"/usr/local/go/src/pkg/github.com/howeyc/fsnotify/fsnotify_symlink_test.go",
"/usr/local/go/src/pkg/github.com/howeyc/fsnotify/fsnotify_test.go",
"/usr/local/go/src/pkg/github.com/howeyc/fsnotify/fsnotify_windows.go",
"/usr/local/go/src/pkg/go/ast/ast.go",
"/usr/local/go/src/pkg/go/ast/ast_test.go",
"/usr/local/go/src/pkg/go/ast/example_test.go",
"/usr/local/go/src/pkg/go/ast/filter.go",
"/usr/local/go/src/pkg/go/ast/import.go",
"/usr/local/go/src/pkg/go/ast/print.go",
"/usr/local/go/src/pkg/go/ast/print_test.go",
"/usr/local/go/src/pkg/go/ast/resolve.go",
"/usr/local/go/src/pkg/go/ast/scope.go",
"/usr/local/go/src/pkg/go/ast/walk.go",
"/usr/local/go/src/pkg/go/build/build.go",
"/usr/local/go/src/pkg/go/build/build_test.go",
"/usr/local/go/src/pkg/go/build/deps_test.go",
"/usr/local/go/src/pkg/go/build/doc.go",
"/usr/local/go/src/pkg/go/build/syslist.go",
"/usr/local/go/src/pkg/go/build/syslist_test.go",
"/usr/local/go/src/pkg/go/build/testdata/other/file/file.go",
"/usr/local/go/src/pkg/go/build/testdata/other/main.go",
"/usr/local/go/src/pkg/go/doc/comment.go",
"/usr/local/go/src/pkg/go/doc/comment_test.go",
"/usr/local/go/src/pkg/go/doc/doc.go",
"/usr/local/go/src/pkg/go/doc/doc_test.go",
"/usr/local/go/src/pkg/go/doc/example.go",
"/usr/local/go/src/pkg/go/doc/exports.go",
"/usr/local/go/src/pkg/go/doc/filter.go",
"/usr/local/go/src/pkg/go/doc/headscan.go",
"/usr/local/go/src/pkg/go/doc/reader.go",
"/usr/local/go/src/pkg/go/doc/synopsis.go",
"/usr/local/go/src/pkg/go/doc/synopsis_test.go",
"/usr/local/go/src/pkg/go/doc/testdata/a0.go",
"/usr/local/go/src/pkg/go/doc/testdata/a1.go",
"/usr/local/go/src/pkg/go/doc/testdata/b.go",
"/usr/local/go/src/pkg/go/doc/testdata/benchmark.go",
"/usr/local/go/src/pkg/go/doc/testdata/c.go",
"/usr/local/go/src/pkg/go/doc/testdata/d1.go",
"/usr/local/go/src/pkg/go/doc/testdata/d2.go",
"/usr/local/go/src/pkg/go/doc/testdata/e.go",
"/usr/local/go/src/pkg/go/doc/testdata/error1.go",
"/usr/local/go/src/pkg/go/doc/testdata/error2.go",
"/usr/local/go/src/pkg/go/doc/testdata/example.go",
"/usr/local/go/src/pkg/go/doc/testdata/f.go",
"/usr/local/go/src/pkg/go/doc/testdata/testing.go",
"/usr/local/go/src/pkg/go/parser/error_test.go",
"/usr/local/go/src/pkg/go/parser/example_test.go",
"/usr/local/go/src/pkg/go/parser/interface.go",
"/usr/local/go/src/pkg/go/parser/parser.go",
"/usr/local/go/src/pkg/go/parser/parser_test.go",
"/usr/local/go/src/pkg/go/parser/short_test.go",
"/usr/local/go/src/pkg/go/printer/example_test.go",
"/usr/local/go/src/pkg/go/printer/nodes.go",
"/usr/local/go/src/pkg/go/printer/performance_test.go",
"/usr/local/go/src/pkg/go/printer/printer.go",
"/usr/local/go/src/pkg/go/printer/printer_test.go",
"/usr/local/go/src/pkg/go/printer/testdata/parser.go",
"/usr/local/go/src/pkg/go/scanner/errors.go",
"/usr/local/go/src/pkg/go/scanner/example_test.go",
"/usr/local/go/src/pkg/go/scanner/scanner.go",
"/usr/local/go/src/pkg/go/scanner/scanner_test.go",
"/usr/local/go/src/pkg/go/token/position.go",
"/usr/local/go/src/pkg/go/token/position_test.go",
"/usr/local/go/src/pkg/go/token/serialize.go",
"/usr/local/go/src/pkg/go/token/serialize_test.go",
"/usr/local/go/src/pkg/go/token/token.go",
"/usr/local/go/src/pkg/hash/adler32/adler32.go",
"/usr/local/go/src/pkg/hash/adler32/adler32_test.go",
"/usr/local/go/src/pkg/hash/crc32/crc32.go",
"/usr/local/go/src/pkg/hash/crc32/crc32_amd64.go",
"/usr/local/go/src/pkg/hash/crc32/crc32_generic.go",
"/usr/local/go/src/pkg/hash/crc32/crc32_test.go",
"/usr/local/go/src/pkg/hash/crc64/crc64.go",
"/usr/local/go/src/pkg/hash/crc64/crc64_test.go",
"/usr/local/go/src/pkg/hash/fnv/fnv.go",
"/usr/local/go/src/pkg/hash/fnv/fnv_test.go",
"/usr/local/go/src/pkg/hash/hash.go",
"/usr/local/go/src/pkg/html/entity.go",
"/usr/local/go/src/pkg/html/entity_test.go",
"/usr/local/go/src/pkg/html/escape.go",
"/usr/local/go/src/pkg/html/template/attr.go",
"/usr/local/go/src/pkg/html/template/clone_test.go",
"/usr/local/go/src/pkg/html/template/content.go",
"/usr/local/go/src/pkg/html/template/content_test.go",
"/usr/local/go/src/pkg/html/template/context.go",
"/usr/local/go/src/pkg/html/template/css.go",
"/usr/local/go/src/pkg/html/template/css_test.go",
"/usr/local/go/src/pkg/html/template/doc.go",
"/usr/local/go/src/pkg/html/template/error.go",
"/usr/local/go/src/pkg/html/template/escape.go",
"/usr/local/go/src/pkg/html/template/escape_test.go",
"/usr/local/go/src/pkg/html/template/html.go",
"/usr/local/go/src/pkg/html/template/html_test.go",
"/usr/local/go/src/pkg/html/template/js.go",
"/usr/local/go/src/pkg/html/template/js_test.go",
"/usr/local/go/src/pkg/html/template/template.go",
"/usr/local/go/src/pkg/html/template/transition.go",
"/usr/local/go/src/pkg/html/template/url.go",
"/usr/local/go/src/pkg/html/template/url_test.go",
"/usr/local/go/src/pkg/image/color/color.go",
"/usr/local/go/src/pkg/image/color/ycbcr.go",
"/usr/local/go/src/pkg/image/color/ycbcr_test.go",
"/usr/local/go/src/pkg/image/decode_example_test.go",
"/usr/local/go/src/pkg/image/decode_test.go",
"/usr/local/go/src/pkg/image/draw/bench_test.go",
"/usr/local/go/src/pkg/image/draw/clip_test.go",
"/usr/local/go/src/pkg/image/draw/draw.go",
"/usr/local/go/src/pkg/image/draw/draw_test.go",
"/usr/local/go/src/pkg/image/format.go",
"/usr/local/go/src/pkg/image/geom.go",
"/usr/local/go/src/pkg/image/gif/reader.go",
"/usr/local/go/src/pkg/image/image.go",
"/usr/local/go/src/pkg/image/image_test.go",
"/usr/local/go/src/pkg/image/jpeg/fdct.go",
"/usr/local/go/src/pkg/image/jpeg/huffman.go",
"/usr/local/go/src/pkg/image/jpeg/idct.go",
"/usr/local/go/src/pkg/image/jpeg/reader.go",
"/usr/local/go/src/pkg/image/jpeg/writer.go",
"/usr/local/go/src/pkg/image/jpeg/writer_test.go",
"/usr/local/go/src/pkg/image/names.go",
"/usr/local/go/src/pkg/image/png/reader.go",
"/usr/local/go/src/pkg/image/png/reader_test.go",
"/usr/local/go/src/pkg/image/png/writer.go",
"/usr/local/go/src/pkg/image/png/writer_test.go",
"/usr/local/go/src/pkg/image/ycbcr.go",
"/usr/local/go/src/pkg/image/ycbcr_test.go",
"/usr/local/go/src/pkg/index/suffixarray/qsufsort.go",
"/usr/local/go/src/pkg/index/suffixarray/suffixarray.go",
"/usr/local/go/src/pkg/index/suffixarray/suffixarray_test.go",
"/usr/local/go/src/pkg/io/io.go",
"/usr/local/go/src/pkg/io/io_test.go",
"/usr/local/go/src/pkg/io/ioutil/ioutil.go",
"/usr/local/go/src/pkg/io/ioutil/ioutil_test.go",
"/usr/local/go/src/pkg/io/ioutil/tempfile.go",
"/usr/local/go/src/pkg/io/ioutil/tempfile_test.go",
"/usr/local/go/src/pkg/io/multi.go",
"/usr/local/go/src/pkg/io/multi_test.go",
"/usr/local/go/src/pkg/io/pipe.go",
"/usr/local/go/src/pkg/io/pipe_test.go",
"/usr/local/go/src/pkg/log/log.go",
"/usr/local/go/src/pkg/log/log_test.go",
"/usr/local/go/src/pkg/log/syslog/syslog.go",
"/usr/local/go/src/pkg/log/syslog/syslog_test.go",
"/usr/local/go/src/pkg/log/syslog/syslog_unix.go",
"/usr/local/go/src/pkg/log/syslog/syslog_windows.go",
"/usr/local/go/src/pkg/math/abs.go",
"/usr/local/go/src/pkg/math/acosh.go",
"/usr/local/go/src/pkg/math/all_test.go",
"/usr/local/go/src/pkg/math/asin.go",
"/usr/local/go/src/pkg/math/asinh.go",
"/usr/local/go/src/pkg/math/atan.go",
"/usr/local/go/src/pkg/math/atan2.go",
"/usr/local/go/src/pkg/math/atanh.go",
"/usr/local/go/src/pkg/math/big/arith.go",
"/usr/local/go/src/pkg/math/big/arith_decl.go",
"/usr/local/go/src/pkg/math/big/arith_test.go",
"/usr/local/go/src/pkg/math/big/calibrate_test.go",
"/usr/local/go/src/pkg/math/big/example_test.go",
"/usr/local/go/src/pkg/math/big/hilbert_test.go",
"/usr/local/go/src/pkg/math/big/int.go",
"/usr/local/go/src/pkg/math/big/int_test.go",
"/usr/local/go/src/pkg/math/big/nat.go",
"/usr/local/go/src/pkg/math/big/nat_test.go",
"/usr/local/go/src/pkg/math/big/rat.go",
"/usr/local/go/src/pkg/math/big/rat_test.go",
"/usr/local/go/src/pkg/math/bits.go",
"/usr/local/go/src/pkg/math/cbrt.go",
"/usr/local/go/src/pkg/math/cmplx/abs.go",
"/usr/local/go/src/pkg/math/cmplx/asin.go",
"/usr/local/go/src/pkg/math/cmplx/cmath_test.go",
"/usr/local/go/src/pkg/math/cmplx/conj.go",
"/usr/local/go/src/pkg/math/cmplx/exp.go",
"/usr/local/go/src/pkg/math/cmplx/isinf.go",
"/usr/local/go/src/pkg/math/cmplx/isnan.go",
"/usr/local/go/src/pkg/math/cmplx/log.go",
"/usr/local/go/src/pkg/math/cmplx/phase.go",
"/usr/local/go/src/pkg/math/cmplx/polar.go",
"/usr/local/go/src/pkg/math/cmplx/pow.go",
"/usr/local/go/src/pkg/math/cmplx/rect.go",
"/usr/local/go/src/pkg/math/cmplx/sin.go",
"/usr/local/go/src/pkg/math/cmplx/sqrt.go",
"/usr/local/go/src/pkg/math/cmplx/tan.go",
"/usr/local/go/src/pkg/math/const.go",
"/usr/local/go/src/pkg/math/copysign.go",
"/usr/local/go/src/pkg/math/dim.go",
"/usr/local/go/src/pkg/math/erf.go",
"/usr/local/go/src/pkg/math/exp.go",
"/usr/local/go/src/pkg/math/expm1.go",
"/usr/local/go/src/pkg/math/export_test.go",
"/usr/local/go/src/pkg/math/floor.go",
"/usr/local/go/src/pkg/math/frexp.go",
"/usr/local/go/src/pkg/math/gamma.go",
"/usr/local/go/src/pkg/math/hypot.go",
"/usr/local/go/src/pkg/math/j0.go",
"/usr/local/go/src/pkg/math/j1.go",
"/usr/local/go/src/pkg/math/jn.go",
"/usr/local/go/src/pkg/math/ldexp.go",
"/usr/local/go/src/pkg/math/lgamma.go",
"/usr/local/go/src/pkg/math/log.go",
"/usr/local/go/src/pkg/math/log10.go",
"/usr/local/go/src/pkg/math/log1p.go",
"/usr/local/go/src/pkg/math/logb.go",
"/usr/local/go/src/pkg/math/mod.go",
"/usr/local/go/src/pkg/math/modf.go",
"/usr/local/go/src/pkg/math/nextafter.go",
"/usr/local/go/src/pkg/math/pow.go",
"/usr/local/go/src/pkg/math/pow10.go",
"/usr/local/go/src/pkg/math/rand/exp.go",
"/usr/local/go/src/pkg/math/rand/normal.go",
"/usr/local/go/src/pkg/math/rand/rand.go",
"/usr/local/go/src/pkg/math/rand/rand_test.go",
"/usr/local/go/src/pkg/math/rand/rng.go",
"/usr/local/go/src/pkg/math/rand/zipf.go",
"/usr/local/go/src/pkg/math/remainder.go",
"/usr/local/go/src/pkg/math/signbit.go",
"/usr/local/go/src/pkg/math/sin.go",
"/usr/local/go/src/pkg/math/sincos.go",
"/usr/local/go/src/pkg/math/sinh.go",
"/usr/local/go/src/pkg/math/sqrt.go",
"/usr/local/go/src/pkg/math/tan.go",
"/usr/local/go/src/pkg/math/tanh.go",
"/usr/local/go/src/pkg/math/unsafe.go",
"/usr/local/go/src/pkg/mime/grammar.go",
"/usr/local/go/src/pkg/mime/mediatype.go",
"/usr/local/go/src/pkg/mime/mediatype_test.go",
"/usr/local/go/src/pkg/mime/multipart/formdata.go",
"/usr/local/go/src/pkg/mime/multipart/formdata_test.go",
"/usr/local/go/src/pkg/mime/multipart/multipart.go",
"/usr/local/go/src/pkg/mime/multipart/multipart_test.go",
"/usr/local/go/src/pkg/mime/multipart/writer.go",
"/usr/local/go/src/pkg/mime/multipart/writer_test.go",
"/usr/local/go/src/pkg/mime/type.go",
"/usr/local/go/src/pkg/mime/type_test.go",
"/usr/local/go/src/pkg/mime/type_unix.go",
"/usr/local/go/src/pkg/mime/type_windows.go",
"/usr/local/go/src/pkg/net/cgo_bsd.go",
"/usr/local/go/src/pkg/net/cgo_linux.go",
"/usr/local/go/src/pkg/net/cgo_stub.go",
"/usr/local/go/src/pkg/net/cgo_unix.go",
"/usr/local/go/src/pkg/net/dial.go",
"/usr/local/go/src/pkg/net/dial_test.go",
"/usr/local/go/src/pkg/net/dialgoogle_test.go",
"/usr/local/go/src/pkg/net/dnsclient.go",
"/usr/local/go/src/pkg/net/dnsclient_unix.go",
"/usr/local/go/src/pkg/net/dnsconfig.go",
"/usr/local/go/src/pkg/net/dnsmsg.go",
"/usr/local/go/src/pkg/net/dnsmsg_test.go",
"/usr/local/go/src/pkg/net/dnsname_test.go",
"/usr/local/go/src/pkg/net/doc.go",
"/usr/local/go/src/pkg/net/example_test.go",
"/usr/local/go/src/pkg/net/fd.go",
"/usr/local/go/src/pkg/net/fd_darwin.go",
"/usr/local/go/src/pkg/net/fd_freebsd.go",
"/usr/local/go/src/pkg/net/fd_linux.go",
"/usr/local/go/src/pkg/net/fd_netbsd.go",
"/usr/local/go/src/pkg/net/fd_openbsd.go",
"/usr/local/go/src/pkg/net/fd_windows.go",
"/usr/local/go/src/pkg/net/file.go",
"/usr/local/go/src/pkg/net/file_plan9.go",
"/usr/local/go/src/pkg/net/file_test.go",
"/usr/local/go/src/pkg/net/file_windows.go",
"/usr/local/go/src/pkg/net/hosts.go",
"/usr/local/go/src/pkg/net/hosts_test.go",
"/usr/local/go/src/pkg/net/http/cgi/child.go",
"/usr/local/go/src/pkg/net/http/cgi/child_test.go",
"/usr/local/go/src/pkg/net/http/cgi/host.go",
"/usr/local/go/src/pkg/net/http/cgi/host_test.go",
"/usr/local/go/src/pkg/net/http/cgi/matryoshka_test.go",
"/usr/local/go/src/pkg/net/http/chunked.go",
"/usr/local/go/src/pkg/net/http/chunked_test.go",
"/usr/local/go/src/pkg/net/http/client.go",
"/usr/local/go/src/pkg/net/http/client_test.go",
"/usr/local/go/src/pkg/net/http/cookie.go",
"/usr/local/go/src/pkg/net/http/cookie_test.go",
"/usr/local/go/src/pkg/net/http/doc.go",
"/usr/local/go/src/pkg/net/http/example_test.go",
"/usr/local/go/src/pkg/net/http/export_test.go",
"/usr/local/go/src/pkg/net/http/fcgi/child.go",
"/usr/local/go/src/pkg/net/http/fcgi/fcgi.go",
"/usr/local/go/src/pkg/net/http/fcgi/fcgi_test.go",
"/usr/local/go/src/pkg/net/http/filetransport.go",
"/usr/local/go/src/pkg/net/http/filetransport_test.go",
"/usr/local/go/src/pkg/net/http/fs.go",
"/usr/local/go/src/pkg/net/http/fs_test.go",
"/usr/local/go/src/pkg/net/http/header.go",
"/usr/local/go/src/pkg/net/http/header_test.go",
"/usr/local/go/src/pkg/net/http/httptest/recorder.go",
"/usr/local/go/src/pkg/net/http/httptest/server.go",
"/usr/local/go/src/pkg/net/http/httptest/server_test.go",
"/usr/local/go/src/pkg/net/http/httputil/chunked.go",
"/usr/local/go/src/pkg/net/http/httputil/chunked_test.go",
"/usr/local/go/src/pkg/net/http/httputil/dump.go",
"/usr/local/go/src/pkg/net/http/httputil/dump_test.go",
"/usr/local/go/src/pkg/net/http/httputil/persist.go",
"/usr/local/go/src/pkg/net/http/httputil/reverseproxy.go",
"/usr/local/go/src/pkg/net/http/httputil/reverseproxy_test.go",
"/usr/local/go/src/pkg/net/http/jar.go",
"/usr/local/go/src/pkg/net/http/lex.go",
"/usr/local/go/src/pkg/net/http/lex_test.go",
"/usr/local/go/src/pkg/net/http/pprof/pprof.go",
"/usr/local/go/src/pkg/net/http/proxy_test.go",
"/usr/local/go/src/pkg/net/http/range_test.go",
"/usr/local/go/src/pkg/net/http/readrequest_test.go",
"/usr/local/go/src/pkg/net/http/request.go",
"/usr/local/go/src/pkg/net/http/request_test.go",
"/usr/local/go/src/pkg/net/http/requestwrite_test.go",
"/usr/local/go/src/pkg/net/http/response.go",
"/usr/local/go/src/pkg/net/http/response_test.go",
"/usr/local/go/src/pkg/net/http/responsewrite_test.go",
"/usr/local/go/src/pkg/net/http/serve_test.go",
"/usr/local/go/src/pkg/net/http/server.go",
"/usr/local/go/src/pkg/net/http/sniff.go",
"/usr/local/go/src/pkg/net/http/sniff_test.go",
"/usr/local/go/src/pkg/net/http/status.go",
"/usr/local/go/src/pkg/net/http/transfer.go",
"/usr/local/go/src/pkg/net/http/transport.go",
"/usr/local/go/src/pkg/net/http/transport_test.go",
"/usr/local/go/src/pkg/net/http/triv.go",
"/usr/local/go/src/pkg/net/interface.go",
"/usr/local/go/src/pkg/net/interface_bsd.go",
"/usr/local/go/src/pkg/net/interface_darwin.go",
"/usr/local/go/src/pkg/net/interface_freebsd.go",
"/usr/local/go/src/pkg/net/interface_linux.go",
"/usr/local/go/src/pkg/net/interface_linux_test.go",
"/usr/local/go/src/pkg/net/interface_netbsd.go",
"/usr/local/go/src/pkg/net/interface_openbsd.go",
"/usr/local/go/src/pkg/net/interface_stub.go",
"/usr/local/go/src/pkg/net/interface_test.go",
"/usr/local/go/src/pkg/net/interface_windows.go",
"/usr/local/go/src/pkg/net/ip.go",
"/usr/local/go/src/pkg/net/ip_test.go",
"/usr/local/go/src/pkg/net/ipraw_test.go",
"/usr/local/go/src/pkg/net/iprawsock.go",
"/usr/local/go/src/pkg/net/iprawsock_plan9.go",
"/usr/local/go/src/pkg/net/iprawsock_posix.go",
"/usr/local/go/src/pkg/net/ipsock.go",
"/usr/local/go/src/pkg/net/ipsock_plan9.go",
"/usr/local/go/src/pkg/net/ipsock_posix.go",
"/usr/local/go/src/pkg/net/lookup_plan9.go",
"/usr/local/go/src/pkg/net/lookup_test.go",
"/usr/local/go/src/pkg/net/lookup_unix.go",
"/usr/local/go/src/pkg/net/lookup_windows.go",
"/usr/local/go/src/pkg/net/mac.go",
"/usr/local/go/src/pkg/net/mac_test.go",
"/usr/local/go/src/pkg/net/mail/message.go",
"/usr/local/go/src/pkg/net/mail/message_test.go",
"/usr/local/go/src/pkg/net/multicast_test.go",
"/usr/local/go/src/pkg/net/net.go",
"/usr/local/go/src/pkg/net/net_posix.go",
"/usr/local/go/src/pkg/net/net_test.go",
"/usr/local/go/src/pkg/net/newpollserver.go",
"/usr/local/go/src/pkg/net/parse.go",
"/usr/local/go/src/pkg/net/parse_test.go",
"/usr/local/go/src/pkg/net/pipe.go",
"/usr/local/go/src/pkg/net/pipe_test.go",
"/usr/local/go/src/pkg/net/port.go",
"/usr/local/go/src/pkg/net/port_test.go",
"/usr/local/go/src/pkg/net/rpc/client.go",
"/usr/local/go/src/pkg/net/rpc/debug.go",
"/usr/local/go/src/pkg/net/rpc/jsonrpc/all_test.go",
"/usr/local/go/src/pkg/net/rpc/jsonrpc/client.go",
"/usr/local/go/src/pkg/net/rpc/jsonrpc/server.go",
"/usr/local/go/src/pkg/net/rpc/server.go",
"/usr/local/go/src/pkg/net/rpc/server_test.go",
"/usr/local/go/src/pkg/net/sendfile_linux.go",
"/usr/local/go/src/pkg/net/sendfile_stub.go",
"/usr/local/go/src/pkg/net/sendfile_windows.go",
"/usr/local/go/src/pkg/net/server_test.go",
"/usr/local/go/src/pkg/net/smtp/auth.go",
"/usr/local/go/src/pkg/net/smtp/smtp.go",
"/usr/local/go/src/pkg/net/smtp/smtp_test.go",
"/usr/local/go/src/pkg/net/sock.go",
"/usr/local/go/src/pkg/net/sock_bsd.go",
"/usr/local/go/src/pkg/net/sock_linux.go",
"/usr/local/go/src/pkg/net/sock_windows.go",
"/usr/local/go/src/pkg/net/sockopt.go",
"/usr/local/go/src/pkg/net/sockopt_bsd.go",
"/usr/local/go/src/pkg/net/sockopt_linux.go",
"/usr/local/go/src/pkg/net/sockopt_windows.go",
"/usr/local/go/src/pkg/net/sockoptip.go",
"/usr/local/go/src/pkg/net/sockoptip_bsd.go",
"/usr/local/go/src/pkg/net/sockoptip_darwin.go",
"/usr/local/go/src/pkg/net/sockoptip_freebsd.go",
"/usr/local/go/src/pkg/net/sockoptip_linux.go",
"/usr/local/go/src/pkg/net/sockoptip_netbsd.go",
"/usr/local/go/src/pkg/net/sockoptip_openbsd.go",
"/usr/local/go/src/pkg/net/sockoptip_windows.go",
"/usr/local/go/src/pkg/net/tcpsock.go",
"/usr/local/go/src/pkg/net/tcpsock_plan9.go",
"/usr/local/go/src/pkg/net/tcpsock_posix.go",
"/usr/local/go/src/pkg/net/textproto/header.go",
"/usr/local/go/src/pkg/net/textproto/pipeline.go",
"/usr/local/go/src/pkg/net/textproto/reader.go",
"/usr/local/go/src/pkg/net/textproto/reader_test.go",
"/usr/local/go/src/pkg/net/textproto/textproto.go",
"/usr/local/go/src/pkg/net/textproto/writer.go",
"/usr/local/go/src/pkg/net/textproto/writer_test.go",
"/usr/local/go/src/pkg/net/timeout_test.go",
"/usr/local/go/src/pkg/net/udp_test.go",
"/usr/local/go/src/pkg/net/udpsock.go",
"/usr/local/go/src/pkg/net/udpsock_plan9.go",
"/usr/local/go/src/pkg/net/udpsock_posix.go",
"/usr/local/go/src/pkg/net/unicast_test.go",
"/usr/local/go/src/pkg/net/unixsock.go",
"/usr/local/go/src/pkg/net/unixsock_plan9.go",
"/usr/local/go/src/pkg/net/unixsock_posix.go",
"/usr/local/go/src/pkg/net/url/example_test.go",
"/usr/local/go/src/pkg/net/url/url.go",
"/usr/local/go/src/pkg/net/url/url_test.go",
"/usr/local/go/src/pkg/os/dir_plan9.go",
"/usr/local/go/src/pkg/os/dir_unix.go",
"/usr/local/go/src/pkg/os/dir_windows.go",
"/usr/local/go/src/pkg/os/doc.go",
"/usr/local/go/src/pkg/os/env.go",
"/usr/local/go/src/pkg/os/env_test.go",
"/usr/local/go/src/pkg/os/error.go",
"/usr/local/go/src/pkg/os/error_plan9.go",
"/usr/local/go/src/pkg/os/error_posix.go",
"/usr/local/go/src/pkg/os/error_test.go",
"/usr/local/go/src/pkg/os/error_windows.go",
"/usr/local/go/src/pkg/os/error_windows_test.go",
"/usr/local/go/src/pkg/os/exec/example_test.go",
"/usr/local/go/src/pkg/os/exec/exec.go",
"/usr/local/go/src/pkg/os/exec/exec_test.go",
"/usr/local/go/src/pkg/os/exec/lp_plan9.go",
"/usr/local/go/src/pkg/os/exec/lp_test.go",
"/usr/local/go/src/pkg/os/exec/lp_unix.go",
"/usr/local/go/src/pkg/os/exec/lp_windows.go",
"/usr/local/go/src/pkg/os/exec.go",
"/usr/local/go/src/pkg/os/exec_plan9.go",
"/usr/local/go/src/pkg/os/exec_posix.go",
"/usr/local/go/src/pkg/os/exec_unix.go",
"/usr/local/go/src/pkg/os/exec_windows.go",
"/usr/local/go/src/pkg/os/export_test.go",
"/usr/local/go/src/pkg/os/file.go",
"/usr/local/go/src/pkg/os/file_plan9.go",
"/usr/local/go/src/pkg/os/file_posix.go",
"/usr/local/go/src/pkg/os/file_unix.go",
"/usr/local/go/src/pkg/os/file_windows.go",
"/usr/local/go/src/pkg/os/getwd.go",
"/usr/local/go/src/pkg/os/os_test.go",
"/usr/local/go/src/pkg/os/os_unix_test.go",
"/usr/local/go/src/pkg/os/path.go",
"/usr/local/go/src/pkg/os/path_plan9.go",
"/usr/local/go/src/pkg/os/path_test.go",
"/usr/local/go/src/pkg/os/path_unix.go",
"/usr/local/go/src/pkg/os/path_windows.go",
"/usr/local/go/src/pkg/os/proc.go",
"/usr/local/go/src/pkg/os/signal/signal.go",
"/usr/local/go/src/pkg/os/signal/signal_stub.go",
"/usr/local/go/src/pkg/os/signal/signal_test.go",
"/usr/local/go/src/pkg/os/signal/signal_unix.go",
"/usr/local/go/src/pkg/os/signal/signal_windows_test.go",
"/usr/local/go/src/pkg/os/stat_darwin.go",
"/usr/local/go/src/pkg/os/stat_freebsd.go",
"/usr/local/go/src/pkg/os/stat_linux.go",
"/usr/local/go/src/pkg/os/stat_netbsd.go",
"/usr/local/go/src/pkg/os/stat_openbsd.go",
"/usr/local/go/src/pkg/os/stat_plan9.go",
"/usr/local/go/src/pkg/os/stat_windows.go",
"/usr/local/go/src/pkg/os/str.go",
"/usr/local/go/src/pkg/os/sys_bsd.go",
"/usr/local/go/src/pkg/os/sys_linux.go",
"/usr/local/go/src/pkg/os/sys_plan9.go",
"/usr/local/go/src/pkg/os/sys_windows.go",
"/usr/local/go/src/pkg/os/types.go",
"/usr/local/go/src/pkg/os/user/lookup_stubs.go",
"/usr/local/go/src/pkg/os/user/lookup_unix.go",
"/usr/local/go/src/pkg/os/user/lookup_windows.go",
"/usr/local/go/src/pkg/os/user/user.go",
"/usr/local/go/src/pkg/os/user/user_test.go",
"/usr/local/go/src/pkg/path/example_test.go",
"/usr/local/go/src/pkg/path/filepath/match.go",
"/usr/local/go/src/pkg/path/filepath/match_test.go",
"/usr/local/go/src/pkg/path/filepath/path.go",
"/usr/local/go/src/pkg/path/filepath/path_plan9.go",
"/usr/local/go/src/pkg/path/filepath/path_test.go",
"/usr/local/go/src/pkg/path/filepath/path_unix.go",
"/usr/local/go/src/pkg/path/filepath/path_windows.go",
"/usr/local/go/src/pkg/path/filepath/symlink.go",
"/usr/local/go/src/pkg/path/filepath/symlink_windows.go",
"/usr/local/go/src/pkg/path/match.go",
"/usr/local/go/src/pkg/path/match_test.go",
"/usr/local/go/src/pkg/path/path.go",
"/usr/local/go/src/pkg/path/path_test.go",
"/usr/local/go/src/pkg/reflect/all_test.go",
"/usr/local/go/src/pkg/reflect/deepequal.go",
"/usr/local/go/src/pkg/reflect/set_test.go",
"/usr/local/go/src/pkg/reflect/tostring_test.go",
"/usr/local/go/src/pkg/reflect/type.go",
"/usr/local/go/src/pkg/reflect/value.go",
"/usr/local/go/src/pkg/regexp/all_test.go",
"/usr/local/go/src/pkg/regexp/exec.go",
"/usr/local/go/src/pkg/regexp/exec_test.go",
"/usr/local/go/src/pkg/regexp/find_test.go",
"/usr/local/go/src/pkg/regexp/regexp.go",
"/usr/local/go/src/pkg/regexp/syntax/compile.go",
"/usr/local/go/src/pkg/regexp/syntax/parse.go",
"/usr/local/go/src/pkg/regexp/syntax/parse_test.go",
"/usr/local/go/src/pkg/regexp/syntax/perl_groups.go",
"/usr/local/go/src/pkg/regexp/syntax/prog.go",
"/usr/local/go/src/pkg/regexp/syntax/prog_test.go",
"/usr/local/go/src/pkg/regexp/syntax/regexp.go",
"/usr/local/go/src/pkg/regexp/syntax/simplify.go",
"/usr/local/go/src/pkg/regexp/syntax/simplify_test.go",
"/usr/local/go/src/pkg/runtime/append_test.go",
"/usr/local/go/src/pkg/runtime/cgo/cgo.go",
"/usr/local/go/src/pkg/runtime/chan_test.go",
"/usr/local/go/src/pkg/runtime/closure_test.go",
"/usr/local/go/src/pkg/runtime/compiler.go",
"/usr/local/go/src/pkg/runtime/debug/stack.go",
"/usr/local/go/src/pkg/runtime/debug/stack_test.go",
"/usr/local/go/src/pkg/runtime/debug.go",
"/usr/local/go/src/pkg/runtime/defs1_linux.go",
"/usr/local/go/src/pkg/runtime/defs2_linux.go",
"/usr/local/go/src/pkg/runtime/defs_arm_linux.go",
"/usr/local/go/src/pkg/runtime/defs_darwin.go",
"/usr/local/go/src/pkg/runtime/defs_freebsd.go",
"/usr/local/go/src/pkg/runtime/defs_linux.go",
"/usr/local/go/src/pkg/runtime/defs_netbsd.go",
"/usr/local/go/src/pkg/runtime/defs_openbsd.go",
"/usr/local/go/src/pkg/runtime/defs_windows.go",
"/usr/local/go/src/pkg/runtime/error.go",
"/usr/local/go/src/pkg/runtime/export_test.go",
"/usr/local/go/src/pkg/runtime/extern.go",
"/usr/local/go/src/pkg/runtime/gc_test.go",
"/usr/local/go/src/pkg/runtime/malloc1.go",
"/usr/local/go/src/pkg/runtime/mallocrand.go",
"/usr/local/go/src/pkg/runtime/mallocrep.go",
"/usr/local/go/src/pkg/runtime/mallocrep1.go",
"/usr/local/go/src/pkg/runtime/mem.go",
"/usr/local/go/src/pkg/runtime/mfinal_test.go",
"/usr/local/go/src/pkg/runtime/pprof/pprof.go",
"/usr/local/go/src/pkg/runtime/pprof/pprof_test.go",
"/usr/local/go/src/pkg/runtime/proc_test.go",
"/usr/local/go/src/pkg/runtime/runtime_linux_test.go",
"/usr/local/go/src/pkg/runtime/runtime_test.go",
"/usr/local/go/src/pkg/runtime/softfloat64.go",
"/usr/local/go/src/pkg/runtime/softfloat64_test.go",
"/usr/local/go/src/pkg/runtime/stack_test.go",
"/usr/local/go/src/pkg/runtime/symtab_test.go",
"/usr/local/go/src/pkg/runtime/syscall_windows_test.go",
"/usr/local/go/src/pkg/runtime/type.go",
"/usr/local/go/src/pkg/runtime/zgoarch_amd64.go",
"/usr/local/go/src/pkg/runtime/zgoos_darwin.go",
"/usr/local/go/src/pkg/runtime/zruntime_defs_darwin_amd64.go",
"/usr/local/go/src/pkg/runtime/zversion.go",
"/usr/local/go/src/pkg/sort/example_interface_test.go",
"/usr/local/go/src/pkg/sort/example_reverse_test.go",
"/usr/local/go/src/pkg/sort/example_test.go",
"/usr/local/go/src/pkg/sort/export_test.go",
"/usr/local/go/src/pkg/sort/search.go",
"/usr/local/go/src/pkg/sort/search_test.go",
"/usr/local/go/src/pkg/sort/sort.go",
"/usr/local/go/src/pkg/sort/sort_test.go",
"/usr/local/go/src/pkg/strconv/atob.go",
"/usr/local/go/src/pkg/strconv/atob_test.go",
"/usr/local/go/src/pkg/strconv/atof.go",
"/usr/local/go/src/pkg/strconv/atof_test.go",
"/usr/local/go/src/pkg/strconv/atoi.go",
"/usr/local/go/src/pkg/strconv/atoi_test.go",
"/usr/local/go/src/pkg/strconv/decimal.go",
"/usr/local/go/src/pkg/strconv/decimal_test.go",
"/usr/local/go/src/pkg/strconv/extfloat.go",
"/usr/local/go/src/pkg/strconv/fp_test.go",
"/usr/local/go/src/pkg/strconv/ftoa.go",
"/usr/local/go/src/pkg/strconv/ftoa_test.go",
"/usr/local/go/src/pkg/strconv/internal_test.go",
"/usr/local/go/src/pkg/strconv/isprint.go",
"/usr/local/go/src/pkg/strconv/itoa.go",
"/usr/local/go/src/pkg/strconv/itoa_test.go",
"/usr/local/go/src/pkg/strconv/makeisprint.go",
"/usr/local/go/src/pkg/strconv/quote.go",
"/usr/local/go/src/pkg/strconv/quote_test.go",
"/usr/local/go/src/pkg/strings/example_test.go",
"/usr/local/go/src/pkg/strings/export_test.go",
"/usr/local/go/src/pkg/strings/reader.go",
"/usr/local/go/src/pkg/strings/reader_test.go",
"/usr/local/go/src/pkg/strings/replace.go",
"/usr/local/go/src/pkg/strings/replace_test.go",
"/usr/local/go/src/pkg/strings/strings.go",
"/usr/local/go/src/pkg/strings/strings_test.go",
"/usr/local/go/src/pkg/sync/atomic/atomic_test.go",
"/usr/local/go/src/pkg/sync/atomic/doc.go",
"/usr/local/go/src/pkg/sync/cond.go",
"/usr/local/go/src/pkg/sync/cond_test.go",
"/usr/local/go/src/pkg/sync/example_test.go",
"/usr/local/go/src/pkg/sync/export_test.go",
"/usr/local/go/src/pkg/sync/mutex.go",
"/usr/local/go/src/pkg/sync/mutex_test.go",
"/usr/local/go/src/pkg/sync/once.go",
"/usr/local/go/src/pkg/sync/once_test.go",
"/usr/local/go/src/pkg/sync/runtime.go",
"/usr/local/go/src/pkg/sync/runtime_sema_test.go",
"/usr/local/go/src/pkg/sync/rwmutex.go",
"/usr/local/go/src/pkg/sync/rwmutex_test.go",
"/usr/local/go/src/pkg/sync/waitgroup.go",
"/usr/local/go/src/pkg/sync/waitgroup_test.go",
"/usr/local/go/src/pkg/syscall/bpf_bsd.go",
"/usr/local/go/src/pkg/syscall/dll_windows.go",
"/usr/local/go/src/pkg/syscall/env_plan9.go",
"/usr/local/go/src/pkg/syscall/env_unix.go",
"/usr/local/go/src/pkg/syscall/env_windows.go",
"/usr/local/go/src/pkg/syscall/exec_bsd.go",
"/usr/local/go/src/pkg/syscall/exec_linux.go",
"/usr/local/go/src/pkg/syscall/exec_plan9.go",
"/usr/local/go/src/pkg/syscall/exec_unix.go",
"/usr/local/go/src/pkg/syscall/exec_windows.go",
"/usr/local/go/src/pkg/syscall/lsf_linux.go",
"/usr/local/go/src/pkg/syscall/netlink_linux.go",
"/usr/local/go/src/pkg/syscall/route_bsd.go",
"/usr/local/go/src/pkg/syscall/route_darwin.go",
"/usr/local/go/src/pkg/syscall/route_freebsd.go",
"/usr/local/go/src/pkg/syscall/route_netbsd.go",
"/usr/local/go/src/pkg/syscall/route_openbsd.go",
"/usr/local/go/src/pkg/syscall/security_windows.go",
"/usr/local/go/src/pkg/syscall/sockcmsg_linux.go",
"/usr/local/go/src/pkg/syscall/sockcmsg_unix.go",
"/usr/local/go/src/pkg/syscall/str.go",
"/usr/local/go/src/pkg/syscall/syscall.go",
"/usr/local/go/src/pkg/syscall/syscall_bsd.go",
"/usr/local/go/src/pkg/syscall/syscall_darwin.go",
"/usr/local/go/src/pkg/syscall/syscall_darwin_386.go",
"/usr/local/go/src/pkg/syscall/syscall_darwin_amd64.go",
"/usr/local/go/src/pkg/syscall/syscall_freebsd.go",
"/usr/local/go/src/pkg/syscall/syscall_freebsd_386.go",
"/usr/local/go/src/pkg/syscall/syscall_freebsd_amd64.go",
"/usr/local/go/src/pkg/syscall/syscall_linux.go",
"/usr/local/go/src/pkg/syscall/syscall_linux_386.go",
"/usr/local/go/src/pkg/syscall/syscall_linux_amd64.go",
"/usr/local/go/src/pkg/syscall/syscall_linux_arm.go",
"/usr/local/go/src/pkg/syscall/syscall_netbsd.go",
"/usr/local/go/src/pkg/syscall/syscall_netbsd_386.go",
"/usr/local/go/src/pkg/syscall/syscall_netbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/syscall_openbsd.go",
"/usr/local/go/src/pkg/syscall/syscall_openbsd_386.go",
"/usr/local/go/src/pkg/syscall/syscall_openbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/syscall_plan9.go",
"/usr/local/go/src/pkg/syscall/syscall_plan9_386.go",
"/usr/local/go/src/pkg/syscall/syscall_unix.go",
"/usr/local/go/src/pkg/syscall/syscall_windows.go",
"/usr/local/go/src/pkg/syscall/syscall_windows_386.go",
"/usr/local/go/src/pkg/syscall/syscall_windows_amd64.go",
"/usr/local/go/src/pkg/syscall/syscall_windows_test.go",
"/usr/local/go/src/pkg/syscall/types_darwin.go",
"/usr/local/go/src/pkg/syscall/types_freebsd.go",
"/usr/local/go/src/pkg/syscall/types_linux.go",
"/usr/local/go/src/pkg/syscall/types_netbsd.go",
"/usr/local/go/src/pkg/syscall/types_openbsd.go",
"/usr/local/go/src/pkg/syscall/zerrors_darwin_386.go",
"/usr/local/go/src/pkg/syscall/zerrors_darwin_amd64.go",
"/usr/local/go/src/pkg/syscall/zerrors_freebsd_386.go",
"/usr/local/go/src/pkg/syscall/zerrors_freebsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zerrors_linux_386.go",
"/usr/local/go/src/pkg/syscall/zerrors_linux_amd64.go",
"/usr/local/go/src/pkg/syscall/zerrors_linux_arm.go",
"/usr/local/go/src/pkg/syscall/zerrors_netbsd_386.go",
"/usr/local/go/src/pkg/syscall/zerrors_netbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zerrors_openbsd_386.go",
"/usr/local/go/src/pkg/syscall/zerrors_openbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zerrors_plan9_386.go",
"/usr/local/go/src/pkg/syscall/zerrors_windows.go",
"/usr/local/go/src/pkg/syscall/zerrors_windows_386.go",
"/usr/local/go/src/pkg/syscall/zerrors_windows_amd64.go",
"/usr/local/go/src/pkg/syscall/zsyscall_darwin_386.go",
"/usr/local/go/src/pkg/syscall/zsyscall_darwin_amd64.go",
"/usr/local/go/src/pkg/syscall/zsyscall_freebsd_386.go",
"/usr/local/go/src/pkg/syscall/zsyscall_freebsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zsyscall_linux_386.go",
"/usr/local/go/src/pkg/syscall/zsyscall_linux_amd64.go",
"/usr/local/go/src/pkg/syscall/zsyscall_linux_arm.go",
"/usr/local/go/src/pkg/syscall/zsyscall_netbsd_386.go",
"/usr/local/go/src/pkg/syscall/zsyscall_netbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zsyscall_openbsd_386.go",
"/usr/local/go/src/pkg/syscall/zsyscall_openbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zsyscall_plan9_386.go",
"/usr/local/go/src/pkg/syscall/zsyscall_windows_386.go",
"/usr/local/go/src/pkg/syscall/zsyscall_windows_amd64.go",
"/usr/local/go/src/pkg/syscall/zsysctl_openbsd.go",
"/usr/local/go/src/pkg/syscall/zsysnum_darwin_386.go",
"/usr/local/go/src/pkg/syscall/zsysnum_darwin_amd64.go",
"/usr/local/go/src/pkg/syscall/zsysnum_freebsd_386.go",
"/usr/local/go/src/pkg/syscall/zsysnum_freebsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zsysnum_linux_386.go",
"/usr/local/go/src/pkg/syscall/zsysnum_linux_amd64.go",
"/usr/local/go/src/pkg/syscall/zsysnum_linux_arm.go",
"/usr/local/go/src/pkg/syscall/zsysnum_netbsd_386.go",
"/usr/local/go/src/pkg/syscall/zsysnum_netbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zsysnum_openbsd_386.go",
"/usr/local/go/src/pkg/syscall/zsysnum_openbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/zsysnum_plan9_386.go",
"/usr/local/go/src/pkg/syscall/zsysnum_windows_386.go",
"/usr/local/go/src/pkg/syscall/zsysnum_windows_amd64.go",
"/usr/local/go/src/pkg/syscall/ztypes_darwin_386.go",
"/usr/local/go/src/pkg/syscall/ztypes_darwin_amd64.go",
"/usr/local/go/src/pkg/syscall/ztypes_freebsd_386.go",
"/usr/local/go/src/pkg/syscall/ztypes_freebsd_amd64.go",
"/usr/local/go/src/pkg/syscall/ztypes_linux_386.go",
"/usr/local/go/src/pkg/syscall/ztypes_linux_amd64.go",
"/usr/local/go/src/pkg/syscall/ztypes_linux_arm.go",
"/usr/local/go/src/pkg/syscall/ztypes_netbsd_386.go",
"/usr/local/go/src/pkg/syscall/ztypes_netbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/ztypes_openbsd_386.go",
"/usr/local/go/src/pkg/syscall/ztypes_openbsd_amd64.go",
"/usr/local/go/src/pkg/syscall/ztypes_plan9_386.go",
"/usr/local/go/src/pkg/syscall/ztypes_windows.go",
"/usr/local/go/src/pkg/syscall/ztypes_windows_386.go",
"/usr/local/go/src/pkg/syscall/ztypes_windows_amd64.go",
"/usr/local/go/src/pkg/testing/benchmark.go",
"/usr/local/go/src/pkg/testing/example.go",
"/usr/local/go/src/pkg/testing/iotest/logger.go",
"/usr/local/go/src/pkg/testing/iotest/reader.go",
"/usr/local/go/src/pkg/testing/iotest/writer.go",
"/usr/local/go/src/pkg/testing/quick/quick.go",
"/usr/local/go/src/pkg/testing/quick/quick_test.go",
"/usr/local/go/src/pkg/testing/testing.go",
"/usr/local/go/src/pkg/text/scanner/scanner.go",
"/usr/local/go/src/pkg/text/scanner/scanner_test.go",
"/usr/local/go/src/pkg/text/tabwriter/example_test.go",
"/usr/local/go/src/pkg/text/tabwriter/tabwriter.go",
"/usr/local/go/src/pkg/text/tabwriter/tabwriter_test.go",
"/usr/local/go/src/pkg/text/template/doc.go",
"/usr/local/go/src/pkg/text/template/example_test.go",
"/usr/local/go/src/pkg/text/template/examplefiles_test.go",
"/usr/local/go/src/pkg/text/template/examplefunc_test.go",
"/usr/local/go/src/pkg/text/template/exec.go",
"/usr/local/go/src/pkg/text/template/exec_test.go",
"/usr/local/go/src/pkg/text/template/funcs.go",
"/usr/local/go/src/pkg/text/template/helper.go",
"/usr/local/go/src/pkg/text/template/multi_test.go",
"/usr/local/go/src/pkg/text/template/parse/lex.go",
"/usr/local/go/src/pkg/text/template/parse/lex_test.go",
"/usr/local/go/src/pkg/text/template/parse/node.go",
"/usr/local/go/src/pkg/text/template/parse/parse.go",
"/usr/local/go/src/pkg/text/template/parse/parse_test.go",
"/usr/local/go/src/pkg/text/template/template.go",
"/usr/local/go/src/pkg/time/example_test.go",
"/usr/local/go/src/pkg/time/format.go",
"/usr/local/go/src/pkg/time/internal_test.go",
"/usr/local/go/src/pkg/time/sleep.go",
"/usr/local/go/src/pkg/time/sleep_test.go",
"/usr/local/go/src/pkg/time/sys_plan9.go",
"/usr/local/go/src/pkg/time/sys_unix.go",
"/usr/local/go/src/pkg/time/sys_windows.go",
"/usr/local/go/src/pkg/time/tick.go",
"/usr/local/go/src/pkg/time/tick_test.go",
"/usr/local/go/src/pkg/time/time.go",
"/usr/local/go/src/pkg/time/time_test.go",
"/usr/local/go/src/pkg/time/zoneinfo.go",
"/usr/local/go/src/pkg/time/zoneinfo_plan9.go",
"/usr/local/go/src/pkg/time/zoneinfo_read.go",
"/usr/local/go/src/pkg/time/zoneinfo_unix.go",
"/usr/local/go/src/pkg/time/zoneinfo_windows.go",
"/usr/local/go/src/pkg/unicode/casetables.go",
"/usr/local/go/src/pkg/unicode/digit.go",
"/usr/local/go/src/pkg/unicode/digit_test.go",
"/usr/local/go/src/pkg/unicode/graphic.go",
"/usr/local/go/src/pkg/unicode/graphic_test.go",
"/usr/local/go/src/pkg/unicode/letter.go",
"/usr/local/go/src/pkg/unicode/letter_test.go",
"/usr/local/go/src/pkg/unicode/maketables.go",
"/usr/local/go/src/pkg/unicode/script_test.go",
"/usr/local/go/src/pkg/unicode/tables.go",
"/usr/local/go/src/pkg/unicode/utf16/export_test.go",
"/usr/local/go/src/pkg/unicode/utf16/utf16.go",
"/usr/local/go/src/pkg/unicode/utf16/utf16_test.go",
"/usr/local/go/src/pkg/unicode/utf8/utf8.go",
"/usr/local/go/src/pkg/unicode/utf8/utf8_test.go",
"/usr/local/go/src/pkg/unsafe/unsafe.go",
}

var c *Chain

func GenerateMainFunc3() string {
	return c.Generate(100)
}

func GenerateProgram() string {
	return "package main; func main() { " + GenerateMainFunc3() + " }"
}

func AppendToFile(name, text string) {
	f, err := os.OpenFile(name, os.O_APPEND|os.O_WRONLY, 0666); CheckError(err)
	defer f.Close()
	f.WriteString(text)
}

func main() {
	for _, v := range alphabet {
		totalProb += v
	}

	// Markov chain init
	c = NewChain(2)     // Initialize a new Chain.
	for _, filename := range filenames {
		f, _ := os.Open(filename)
		defer f.Close()
		c.Build(f)
	}
	println("Chain size", len(c.chain))

	rand.Seed(time.Now().UnixNano())

	if false {
		for i := 0; i < 100; i++ {
			main := GenerateMainFunc3()
			println(main)
			println("----------------------------------------")
		}
		return
	}

	// Create log file if it doesn't exist (so we can append stuff to it)
	/*if !FileExists("./Gen/Log.txt") {
		f, err := os.Create("./Gen/Log.txt"); CheckError(err)
		err = f.Close(); CheckError(err)
	}*/

	var Good, Tries int
	startTime := time.Now()

	now := time.Now()
	fmt.Printf("\n\n%v %v STARTED Stats: %v/%v good/tries\n", now.Unix(), now, Good, Tries)
	//AppendToFile("./Gen/Log.txt", fmt.Sprintf("\n\n%v %v STARTED Stats: %v/%v good/tries\n", now.Unix(), now, Good, Tries))

	//for i := 0; i < 5000; i++ {
	for {
		f, err := os.Create("./Gen/GenProgram.go"); CheckError(err)
		defer os.Remove(f.Name())

		prog := GenerateProgram()
		f.WriteString(prog)

		err = f.Close(); CheckError(err)

		err = exec.Command("/usr/local/go/bin/go", "build", "-o", "./Gen/Out", f.Name()).Run()
		defer os.Remove("./Gen/Out")
		now = time.Now()
		Tries = Tries + 1
		if (nil == err && FileExists("./Gen/Out")) {
			Good = Good + 1
			fmt.Printf(" %v %v OMG SUCCESS: %s\n", now.Unix(), now, prog)
			//AppendToFile("./Gen/Log.txt", fmt.Sprintf(" %v %v OMG SUCCESS: %s\n", now.Unix(), now, prog))
		} else {
			//fmt.Printf(" %v %v Fail... err: %v\n", now.Unix(), now, err)
		}

		if 0 == Tries % 1000 {
			successRate := float64(Good) / float64(Tries) * 100
			opsPerSec := float64(Tries) / time.Since(startTime).Seconds()
			fmt.Printf("%v %v Stats: %v/%v (%v%%) good/tries, %v ops/sec\n", now.Unix(), now, Good, Tries, successRate, opsPerSec)
			//AppendToFile("./Gen/Log.txt", fmt.Sprintf("%v %v Stats: %v/%v (%v%%) good/tries, %v ops/sec\n", now.Unix(), now, Good, Tries, successRate, opsPerSec))
		}
		//time.Sleep(time.Millisecond)
	}

	now = time.Now()
	fmt.Printf("%v %v FINISHED Stats: %v/%v (%v%%) good/tries\n\n", now.Unix(), now, Good, Tries, float64(Good) / float64(Tries) * 100)
	//AppendToFile("./Gen/Log.txt", fmt.Sprintf("%v %v FINISHED Stats: %v/%v (%v%%) good/tries\n\n", now.Unix(), now, Good, Tries, float64(Good) / float64(Tries) * 100))
}