package main

const in = `diff --git a/config.go b/config.go
index 7c3fdd4..efe023a 100644
--- a/config.go
+++ b/config.go
@@ -103,6 +103,8 @@ type srcfileConfig struct {
 	// TODO(samer): Make sure that configs do not use this option
 	// and remove it by May 4th.
 	ImportFromBinary bool
+
+	SkipGodeps bool
 }

 // unmarshalTypedConfig parses config from the Config field of the source unit.
@@ -171,7 +173,7 @@ func (c *srcfileConfig) apply() error {
 		}
 		config.GOPATH = strings.Join(dirs, string(filepath.ListSeparator))

-		buildContext.GOPATH += string(filepath.ListSeparator) + config.GOPATH
+		buildContext.GOPATH = config.GOPATH + string(filepath.ListSeparator) + buildContext.GOPATH
 		loaderConfig.Build = &buildContext
 	}

diff --git a/scan.go b/scan.go
index 8ce6c5d..d726c74 100644
--- a/scan.go
+++ b/scan.go
@@ -2,13 +2,12 @@ package main

 import (
 	"encoding/json"
-	"fmt"
 	"go/build"
-	"io"
+	"io/ioutil"
 	"log"
 	"os"
-	"os/exec"
 	"path/filepath"
+	"regexp"
 	"sort"
 	"strings"

@@ -89,15 +88,29 @@ func (c *ScanCmd) Execute(args []string) error {
 		}
 	}

-	pkgPatterns := []string{"./..."}
-	if config.PkgPatterns != nil {
-		pkgPatterns = config.PkgPatterns
-	}
-	units, err := scan(pkgPatterns, scanDir)
+	units, err := scan(scanDir)
 	if err != nil {
 		return err
 	}

+	if len(config.PkgPatterns) != 0 {
+		matchers := make([]func(name string) bool, len(config.PkgPatterns))
+		for i, pattern := range config.PkgPatterns {
+			matchers[i] = matchPattern(pattern)
+		}
+
+		var filteredUnits []*unit.SourceUnit
+		for _, unit := range units {
+			for _, m := range matchers {
+				if m(unit.Name) {
+					filteredUnits = append(filteredUnits, unit)
+					break
+				}
+			}
+		}
+		units = filteredUnits
+	}
+
 	// Fix up import paths to be consistent when running as a program and as
 	// a Docker container. But if a GOROOT is set, then we probably want import
 	// paths to not contain the repo, so only do this if there's no GOROOT set
@@ -183,33 +196,17 @@ func isInGopath(path string) bool {
 	return false
 }

-func scan(pkgPatterns []string, scanDir string) ([]*unit.SourceUnit, error) {
+func scan(scanDir string) ([]*unit.SourceUnit, error) {
 	// TODO(sqs): include xtest, but we'll have to make them have a distinctly
 	// namespaced def path from the non-xtest pkg.

-	// Go always evaluates symlinks in the working directory path, using sh is a workaround
-	cmd := exec.Command("sh", "-c", fmt.Sprintf(` + "`" + `cd %s; %s list -e -json %s` + "`" + `, scanDir, goBinaryName, strings.Join(pkgPatterns, " ")))
-	cmd.Env = config.env()
-	cmd.Stderr = os.Stderr
-	stdout, err := cmd.StdoutPipe()
+	pkgs, err := scanForPackages(scanDir)
 	if err != nil {
 		return nil, err
 	}
-	if err := cmd.Start(); err != nil {
-		return nil, err
-	}

-	dec := json.NewDecoder(stdout)
 	var units []*unit.SourceUnit
-	for {
-		var pkg *build.Package
-		if err := dec.Decode(&pkg); err != nil {
-			if err == io.EOF {
-				break
-			}
-			return nil, err
-		}
-
+	for _, pkg := range pkgs {
 		// Collect all files
 		var files []string
 		files = append(files, pkg.GoFiles...)
@@ -240,27 +237,23 @@ func scan(pkgPatterns []string, scanDir string) ([]*unit.SourceUnit, error) {
 			deps[i] = imp
 		}

-		// Make all dirs relative to the current one.
-		makeRel := func(dirs ...*string) (err error) {
-			for _, d := range dirs {
-				if *d == "" {
-					continue
-				}
-				*d, err = filepath.Rel(scanDir, *d)
-				if err != nil {
-					return err
-				}
-			}
-			return nil
-		}
-		if err := makeRel(&pkg.Dir, &pkg.BinDir, &pkg.ConflictDir); err != nil {
+		pkg.Dir, err = filepath.Rel(scanDir, pkg.Dir)
+		if err != nil {
 			return nil, err
 		}
+		pkg.BinDir = ""
+		pkg.ConflictDir = ""

 		// Root differs depending on the system, so it's hard to compare results
 		// across environments (when running as a program). Clear it so we can
 		// compare results in tests more easily.
 		pkg.Root = ""
+		pkg.SrcRoot = ""
+		pkg.PkgRoot = ""
+
+		pkg.ImportPos = nil
+		pkg.TestImportPos = nil
+		pkg.XTestImportPos = nil

 		units = append(units, &unit.SourceUnit{
 			Name:         pkg.ImportPath,
@@ -272,9 +265,53 @@ func scan(pkgPatterns []string, scanDir string) ([]*unit.SourceUnit, error) {
 			Ops:          map[string]*srclib.ToolRef{"depresolve": nil, "graph": nil},
 		})
 	}
-	if err := cmd.Wait(); err != nil {
+
+	return units, nil
+}
+
+func scanForPackages(dir string) ([]*build.Package, error) {
+	var pkgs []*build.Package
+
+	pkg, err := buildContext.ImportDir(dir, 0)
+	if _, isNoGoError := err.(*build.NoGoError); err != nil && !isNoGoError {
 		return nil, err
 	}
+	if err == nil {
+		pkgs = append(pkgs, pkg)
+	}

-	return units, nil
+	infos, err := ioutil.ReadDir(dir)
+	if err != nil {
+		return nil, err
+	}
+	for _, info := range infos {
+		name := info.Name()
+		fullPath := filepath.Join(dir, name)
+		if info.IsDir() && ((name[0] != '.' && name[0] != '_' && name != "testdata") || (strings.HasSuffix(fullPath, "Godeps/_workspace") && !config.SkipGodeps)) {
+			subPkgs, err := scanForPackages(fullPath)
+			if err != nil {
+				return nil, err
+			}
+			pkgs = append(pkgs, subPkgs...)
+		}
+	}
+
+	return pkgs, nil
+}
+
+// matchPattern(pattern)(name) reports whether
+// name matches pattern.  Pattern is a limited glob
+// pattern in which '...' means 'any string' and there
+// is no other special syntax.
+func matchPattern(pattern string) func(name string) bool {
+	re := regexp.QuoteMeta(pattern)
+	re = strings.Replace(re, ` + "`" + `\.\.\.` + "`" + `, ` + "`" + `.*` + "`" + `, -1)
+	// Special case: foo/... matches foo too.
+	if strings.HasSuffix(re, ` + "`" + `/.*` + "`" + `) {
+		re = re[:len(re)-len(` + "`" + `/.*` + "`" + `)] + ` + "`" + `(/.*)?` + "`" + `
+	}
+	reg := regexp.MustCompile(` + "`" + `^` + "`" + ` + re + ` + "`" + `$` + "`" + `)
+	return func(name string) bool {
+		return reg.MatchString(name)
+	}
 }
diff --git a/testdata/expected/docker/cgo_sample/github.com/sgtest/cgo_sample/GoPackage.unit.json b/testdata/expected/docker/cgo_sample/github.com/sgtest/cgo_sample/GoPackage.unit.json
index 0f1e4f8..27c0874 100644
--- a/testdata/expected/docker/cgo_sample/github.com/sgtest/cgo_sample/GoPackage.unit.json
+++ b/testdata/expected/docker/cgo_sample/github.com/sgtest/cgo_sample/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/cgo_sample","Type":"GoPackage","Repo":"github.com/sgtest/cgo_sample","Files":["bar.go","foo.go"],"Dir":".","Dependencies":["C","fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":["foo.go"],"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["bar.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/cgo_sample","ImportPos":null,"Imports":["C","fmt"],"MFiles":null,"Name":"cgo_sample","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/cgo_sample","Type":"GoPackage","Repo":"github.com/sgtest/cgo_sample","Files":["bar.go","foo.go"],"Dir":".","Dependencies":["C","fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":["foo.go"],"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["bar.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/cgo_sample","ImportPos":null,"Imports":["C","fmt"],"MFiles":null,"Name":"cgo_sample","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/exported_methods/GoPackage.unit.json b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/exported_methods/GoPackage.unit.json
index b9c0877..9cfec86 100644
--- a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/exported_methods/GoPackage.unit.json
+++ b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/exported_methods/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/go-misc/exported_methods","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["exported_methods/exported_methods.go"],"Dir":"exported_methods","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"exported_methods","Doc":"Package exported_methods tests that srclib-go exports all capitalized methods, even if the type that the method is on is unexported.","GoFiles":["exported_methods.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/exported_methods","ImportPos":null,"Imports":null,"MFiles":null,"Name":"exported_methods","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/go-misc/exported_methods","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["exported_methods/exported_methods.go"],"Dir":"exported_methods","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"exported_methods","Doc":"Package exported_methods tests that srclib-go exports all capitalized methods, even if the type that the method is on is unexported.","GoFiles":["exported_methods.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/exported_methods","ImportPos":null,"Imports":[],"MFiles":null,"Name":"exported_methods","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/go_subrepo_import/GoPackage.unit.json b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/go_subrepo_import/GoPackage.unit.json
index d5f5fbc..53f1a46 100644
--- a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/go_subrepo_import/GoPackage.unit.json
+++ b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/go_subrepo_import/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/go-misc/go_subrepo_import","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["go_subrepo_import/go_subrepo_import.go"],"Dir":"go_subrepo_import","Dependencies":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go_subrepo_import","Doc":"Package go_subrepo_import tests that srclib-go properly resolves imports of Go subrepositories (golang.org/x/*).","GoFiles":["go_subrepo_import.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/go_subrepo_import","ImportPos":null,"Imports":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"MFiles":null,"Name":"go_subrepo_import","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/go-misc/go_subrepo_import","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["go_subrepo_import/go_subrepo_import.go"],"Dir":"go_subrepo_import","Dependencies":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go_subrepo_import","Doc":"Package go_subrepo_import tests that srclib-go properly resolves imports of Go subrepositories (golang.org/x/*).","GoFiles":["go_subrepo_import.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/go_subrepo_import","ImportPos":null,"Imports":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"MFiles":null,"Name":"go_subrepo_import","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/multiple_mains/GoPackage.unit.json b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/multiple_mains/GoPackage.unit.json
index 30bc8ef..3026466 100644
--- a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/multiple_mains/GoPackage.unit.json
+++ b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/multiple_mains/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/go-misc/multiple_mains","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["multiple_mains/main1.go","multiple_mains/main2.go"],"Dir":"multiple_mains","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"multiple_mains","Doc":"","GoFiles":["main1.go","main2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/multiple_mains","ImportPos":null,"Imports":null,"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/go-misc/multiple_mains","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["multiple_mains/main1.go","multiple_mains/main2.go"],"Dir":"multiple_mains","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"multiple_mains","Doc":"","GoFiles":["main1.go","main2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/multiple_mains","ImportPos":null,"Imports":[],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/scope/GoPackage.unit.json b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/scope/GoPackage.unit.json
index 4de8c79..f09b601 100644
--- a/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/scope/GoPackage.unit.json
+++ b/testdata/expected/docker/go-misc/github.com/sgtest/go-misc/scope/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/go-misc/scope","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["scope/scope.go"],"Dir":"scope","Dependencies":["fmt","strings"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"scope","Doc":"This package tests Exported and Local.","GoFiles":["scope.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/scope","ImportPos":null,"Imports":["fmt","strings"],"MFiles":null,"Name":"scope","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/go-misc/scope","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["scope/scope.go"],"Dir":"scope","Dependencies":["fmt","strings"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"scope","Doc":"This package tests Exported and Local.","GoFiles":["scope.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-misc/scope","ImportPos":null,"Imports":["fmt","strings"],"MFiles":null,"Name":"scope","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/go-sample-0/github.com/sgtest/go-sample-0/mypkg/GoPackage.unit.json b/testdata/expected/docker/go-sample-0/github.com/sgtest/go-sample-0/mypkg/GoPackage.unit.json
index 64310c6..bfa8d09 100644
--- a/testdata/expected/docker/go-sample-0/github.com/sgtest/go-sample-0/mypkg/GoPackage.unit.json
+++ b/testdata/expected/docker/go-sample-0/github.com/sgtest/go-sample-0/mypkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/go-sample-0/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/go-sample-0","Files":["mypkg/bar.go","mypkg/foo.go"],"Dir":"mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"mypkg","Doc":"","GoFiles":["bar.go","foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-sample-0/mypkg","ImportPos":null,"Imports":null,"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/go-sample-0/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/go-sample-0","Files":["mypkg/bar.go","mypkg/foo.go"],"Dir":"mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"mypkg","Doc":"","GoFiles":["bar.go","foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-sample-0/mypkg","ImportPos":null,"Imports":[],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/go-testonly/github.com/sgtest/go-testonly/GoPackage.unit.json b/testdata/expected/docker/go-testonly/github.com/sgtest/go-testonly/GoPackage.unit.json
index 3e4a3a9..acf9748 100644
--- a/testdata/expected/docker/go-testonly/github.com/sgtest/go-testonly/GoPackage.unit.json
+++ b/testdata/expected/docker/go-testonly/github.com/sgtest/go-testonly/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/go-testonly","Type":"GoPackage","Repo":"github.com/sgtest/go-testonly","Files":["foo_test.go"],"Dir":".","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":null,"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-testonly","ImportPos":null,"Imports":null,"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["foo_test.go"],"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/go-testonly","Type":"GoPackage","Repo":"github.com/sgtest/go-testonly","Files":["foo_test.go"],"Dir":".","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":null,"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go-testonly","ImportPos":null,"Imports":[],"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["foo_test.go"],"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/go13-sample/github.com/sgtest/go13-sample/GoPackage.unit.json b/testdata/expected/docker/go13-sample/github.com/sgtest/go13-sample/GoPackage.unit.json
index 894e182..24e36ae 100644
--- a/testdata/expected/docker/go13-sample/github.com/sgtest/go13-sample/GoPackage.unit.json
+++ b/testdata/expected/docker/go13-sample/github.com/sgtest/go13-sample/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/go13-sample","Type":"GoPackage","Repo":"github.com/sgtest/go13-sample","Files":["go13sample.go"],"Dir":".","Dependencies":["fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["go13sample.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go13-sample","ImportPos":null,"Imports":["fmt"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOVERSION":"1.3"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/go13-sample","Type":"GoPackage","Repo":"github.com/sgtest/go13-sample","Files":["go13sample.go"],"Dir":".","Dependencies":["fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["go13sample.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/go13-sample","ImportPos":null,"Imports":["fmt"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOVERSION":"1.3"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json b/testdata/expected/docker/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json
index 55a5950..2e91015 100644
--- a/testdata/expected/docker/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json
+++ b/testdata/expected/docker/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"mycompany.example.com/foo","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/foo/foo.go"],"Dir":"go/src/mycompany.example.com/foo","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/foo","Doc":"","GoFiles":["foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/foo","ImportPos":null,"Imports":null,"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"mycompany.example.com/foo","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/foo/foo.go"],"Dir":"go/src/mycompany.example.com/foo","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/foo","Doc":"","GoFiles":["foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/foo","ImportPos":null,"Imports":[],"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json b/testdata/expected/docker/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json
index ba00391..145c2cd 100644
--- a/testdata/expected/docker/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json
+++ b/testdata/expected/docker/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"mycompany.example.com/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/mypkg/mypkg.go"],"Dir":"go/src/mycompany.example.com/mypkg","Dependencies":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/mypkg","Doc":"","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/mypkg","ImportPos":null,"Imports":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"mycompany.example.com/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/mypkg/mypkg.go"],"Dir":"go/src/mycompany.example.com/mypkg","Dependencies":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/mypkg","Doc":"","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/mypkg","ImportPos":null,"Imports":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json b/testdata/expected/docker/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json
index 241539f..5d80389 100644
--- a/testdata/expected/docker/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json
+++ b/testdata/expected/docker/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"othercompany.example.com/otherpkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/othercompany.example.com/otherpkg/otherpkg.go"],"Dir":"go/src/othercompany.example.com/otherpkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/othercompany.example.com/otherpkg","Doc":"","GoFiles":["otherpkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"othercompany.example.com/otherpkg","ImportPos":null,"Imports":null,"MFiles":null,"Name":"otherpkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"othercompany.example.com/otherpkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/othercompany.example.com/otherpkg/otherpkg.go"],"Dir":"go/src/othercompany.example.com/otherpkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/othercompany.example.com/otherpkg","Doc":"","GoFiles":["otherpkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"othercompany.example.com/otherpkg","ImportPos":null,"Imports":[],"MFiles":null,"Name":"otherpkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/gopathtest/github.com/alice/mypkg/GoPackage.unit.json b/testdata/expected/docker/gopathtest/github.com/alice/mypkg/GoPackage.unit.json
index 1ddd9a2..b77ff46 100644
--- a/testdata/expected/docker/gopathtest/github.com/alice/mypkg/GoPackage.unit.json
+++ b/testdata/expected/docker/gopathtest/github.com/alice/mypkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/alice/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg/mypkg.go"],"Dir":"vendor/src/github.com/alice/mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg","Doc":"Package mypkg is a vendored dependency.","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg","ImportPos":null,"Imports":null,"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/alice/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg/mypkg.go"],"Dir":"vendor/src/github.com/alice/mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg","Doc":"Package mypkg is a vendored dependency.","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg","ImportPos":null,"Imports":[],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json b/testdata/expected/docker/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json
index 0719eb6..67fb0d0 100644
--- a/testdata/expected/docker/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json
+++ b/testdata/expected/docker/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/alice/mypkg2","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg2/mypkg2.go"],"Dir":"vendor/src/github.com/alice/mypkg2","Dependencies":["github.com/alice/mypkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg2","Doc":"Package mypkg2 tests that it can import a vendored dep.","GoFiles":["mypkg2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg2","ImportPos":null,"Imports":["github.com/alice/mypkg"],"MFiles":null,"Name":"mypkg2","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/alice/mypkg2","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg2/mypkg2.go"],"Dir":"vendor/src/github.com/alice/mypkg2","Dependencies":["github.com/alice/mypkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg2","Doc":"Package mypkg2 tests that it can import a vendored dep.","GoFiles":["mypkg2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg2","ImportPos":null,"Imports":["github.com/alice/mypkg"],"MFiles":null,"Name":"mypkg2","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/gopathtest/github.com/sgtest/gopathtest/GoPackage.unit.json b/testdata/expected/docker/gopathtest/github.com/sgtest/gopathtest/GoPackage.unit.json
index 5cd6967..afee73d 100644
--- a/testdata/expected/docker/gopathtest/github.com/sgtest/gopathtest/GoPackage.unit.json
+++ b/testdata/expected/docker/gopathtest/github.com/sgtest/gopathtest/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/sgtest/gopathtest","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["gopathtest.go"],"Dir":".","Dependencies":["github.com/alice/mypkg","github.com/alice/mypkg2"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"Package gopathtest tests that it can access vendored deps in vendor/.","GoFiles":["gopathtest.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/gopathtest","ImportPos":null,"Imports":["github.com/alice/mypkg","github.com/alice/mypkg2"],"MFiles":null,"Name":"gopathtest","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/sgtest/gopathtest","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["gopathtest.go"],"Dir":".","Dependencies":["github.com/alice/mypkg","github.com/alice/mypkg2"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"Package gopathtest tests that it can access vendored deps in vendor/.","GoFiles":["gopathtest.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/sgtest/gopathtest","ImportPos":null,"Imports":["github.com/alice/mypkg","github.com/alice/mypkg2"],"MFiles":null,"Name":"gopathtest","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/minimal-go-stdlib/cmd/go/GoPackage.unit.json b/testdata/expected/docker/minimal-go-stdlib/cmd/go/GoPackage.unit.json
index 058927b..94feb2a 100644
--- a/testdata/expected/docker/minimal-go-stdlib/cmd/go/GoPackage.unit.json
+++ b/testdata/expected/docker/minimal-go-stdlib/cmd/go/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"cmd/go","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/cmd/go/main.go"],"Dir":"src/cmd/go","Dependencies":["dummy0"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/cmd/go","Doc":"","GoFiles":["main.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"cmd/go","ImportPos":null,"Imports":["dummy0"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"cmd/go","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/cmd/go/main.go"],"Dir":"src/cmd/go","Dependencies":["dummy0"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/cmd/go","Doc":"","GoFiles":["main.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"cmd/go","ImportPos":null,"Imports":["dummy0"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/minimal-go-stdlib/dummy0/GoPackage.unit.json b/testdata/expected/docker/minimal-go-stdlib/dummy0/GoPackage.unit.json
index 68bb3ca..0c6d8b4 100644
--- a/testdata/expected/docker/minimal-go-stdlib/dummy0/GoPackage.unit.json
+++ b/testdata/expected/docker/minimal-go-stdlib/dummy0/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"dummy0","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy0/dummy0.go","src/dummy0/dummy0_test.go"],"Dir":"src/dummy0","Dependencies":["dummy1","fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy0","Doc":"","GoFiles":["dummy0.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy0","ImportPos":null,"Imports":["dummy1","fmt"],"MFiles":null,"Name":"dummy0","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["dummy0_test.go"],"TestImportPos":null,"TestImports":["dummy1"],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"dummy0","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy0/dummy0.go","src/dummy0/dummy0_test.go"],"Dir":"src/dummy0","Dependencies":["dummy1","fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy0","Doc":"","GoFiles":["dummy0.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy0","ImportPos":null,"Imports":["dummy1","fmt"],"MFiles":null,"Name":"dummy0","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["dummy0_test.go"],"TestImportPos":null,"TestImports":["dummy1"],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/minimal-go-stdlib/dummy1/GoPackage.unit.json b/testdata/expected/docker/minimal-go-stdlib/dummy1/GoPackage.unit.json
index b8a4013..5c3e949 100644
--- a/testdata/expected/docker/minimal-go-stdlib/dummy1/GoPackage.unit.json
+++ b/testdata/expected/docker/minimal-go-stdlib/dummy1/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"dummy1","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy1/dummy1.go","src/dummy1/dummy1_x_test.go"],"Dir":"src/dummy1","Dependencies":["dummy1"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy1","Doc":"","GoFiles":["dummy1.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy1","ImportPos":null,"Imports":null,"MFiles":null,"Name":"dummy1","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":["dummy1_x_test.go"],"XTestImportPos":null,"XTestImports":["dummy1"]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"dummy1","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy1/dummy1.go","src/dummy1/dummy1_x_test.go"],"Dir":"src/dummy1","Dependencies":["dummy1"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy1","Doc":"","GoFiles":["dummy1.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy1","ImportPos":null,"Imports":[],"MFiles":null,"Name":"dummy1","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":["dummy1_x_test.go"],"XTestImportPos":null,"XTestImports":["dummy1"]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/minimal-go-stdlib/fmt/GoPackage.unit.json b/testdata/expected/docker/minimal-go-stdlib/fmt/GoPackage.unit.json
index 44838ee..ffc3f48 100644
--- a/testdata/expected/docker/minimal-go-stdlib/fmt/GoPackage.unit.json
+++ b/testdata/expected/docker/minimal-go-stdlib/fmt/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"fmt","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/fmt/fake_fmt.go"],"Dir":"src/fmt","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/fmt","Doc":"","GoFiles":["fake_fmt.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"fmt","ImportPos":null,"Imports":null,"MFiles":null,"Name":"fmt","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"fmt","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/fmt/fake_fmt.go"],"Dir":"src/fmt","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/fmt","Doc":"","GoFiles":["fake_fmt.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"fmt","ImportPos":null,"Imports":[],"MFiles":null,"Name":"fmt","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/docker/minimal-go-stdlib/runtime/GoPackage.unit.json b/testdata/expected/docker/minimal-go-stdlib/runtime/GoPackage.unit.json
index 1212743..aee62a7 100644
--- a/testdata/expected/docker/minimal-go-stdlib/runtime/GoPackage.unit.json
+++ b/testdata/expected/docker/minimal-go-stdlib/runtime/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"runtime","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/runtime/runtime.go"],"Dir":"src/runtime","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/runtime","Doc":"","GoFiles":["runtime.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"runtime","ImportPos":null,"Imports":null,"MFiles":null,"Name":"runtime","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"runtime","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/runtime/runtime.go"],"Dir":"src/runtime","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/runtime","Doc":"","GoFiles":["runtime.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"runtime","ImportPos":null,"Imports":[],"MFiles":null,"Name":"runtime","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/cgo_sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample/GoPackage.unit.json b/testdata/expected/program/cgo_sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample/GoPackage.unit.json
index 916d7d8..e1314ee 100644
--- a/testdata/expected/program/cgo_sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample/GoPackage.unit.json
+++ b/testdata/expected/program/cgo_sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample","Type":"GoPackage","Repo":"github.com/sgtest/cgo_sample","Files":["bar.go","foo.go"],"Dir":".","Dependencies":["C","fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":["foo.go"],"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["bar.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample","ImportPos":null,"Imports":["C","fmt"],"MFiles":null,"Name":"cgo_sample","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample","Type":"GoPackage","Repo":"github.com/sgtest/cgo_sample","Files":["bar.go","foo.go"],"Dir":".","Dependencies":["C","fmt"],"Data":{"AllTags":["cgo"],"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":["foo.go"],"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["bar.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/cgo_sample","ImportPos":null,"Imports":["C","fmt"],"MFiles":null,"Name":"cgo_sample","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods/GoPackage.unit.json b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods/GoPackage.unit.json
index 84f60c7..0a2d7c6 100644
--- a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods/GoPackage.unit.json
+++ b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["exported_methods/exported_methods.go"],"Dir":"exported_methods","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"exported_methods","Doc":"Package exported_methods tests that srclib-go exports all capitalized methods, even if the type that the method is on is unexported.","GoFiles":["exported_methods.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods","ImportPos":null,"Imports":null,"MFiles":null,"Name":"exported_methods","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["exported_methods/exported_methods.go"],"Dir":"exported_methods","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"exported_methods","Doc":"Package exported_methods tests that srclib-go exports all capitalized methods, even if the type that the method is on is unexported.","GoFiles":["exported_methods.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/exported_methods","ImportPos":null,"Imports":[],"MFiles":null,"Name":"exported_methods","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import/GoPackage.unit.json b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import/GoPackage.unit.json
index 358cf96..40d8869 100644
--- a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import/GoPackage.unit.json
+++ b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["go_subrepo_import/go_subrepo_import.go"],"Dir":"go_subrepo_import","Dependencies":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go_subrepo_import","Doc":"Package go_subrepo_import tests that srclib-go properly resolves imports of Go subrepositories (golang.org/x/*).","GoFiles":["go_subrepo_import.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import","ImportPos":null,"Imports":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"MFiles":null,"Name":"go_subrepo_import","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["go_subrepo_import/go_subrepo_import.go"],"Dir":"go_subrepo_import","Dependencies":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go_subrepo_import","Doc":"Package go_subrepo_import tests that srclib-go properly resolves imports of Go subrepositories (golang.org/x/*).","GoFiles":["go_subrepo_import.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/go_subrepo_import","ImportPos":null,"Imports":["golang.org/x/net/ipv6","golang.org/x/tools/go/types"],"MFiles":null,"Name":"go_subrepo_import","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains/GoPackage.unit.json b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains/GoPackage.unit.json
index 4b7acc6..39f1330 100644
--- a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains/GoPackage.unit.json
+++ b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["multiple_mains/main1.go","multiple_mains/main2.go"],"Dir":"multiple_mains","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"multiple_mains","Doc":"","GoFiles":["main1.go","main2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains","ImportPos":null,"Imports":null,"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["multiple_mains/main1.go","multiple_mains/main2.go"],"Dir":"multiple_mains","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"multiple_mains","Doc":"","GoFiles":["main1.go","main2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/multiple_mains","ImportPos":null,"Imports":[],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope/GoPackage.unit.json b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope/GoPackage.unit.json
index 0f39e58..f777c56 100644
--- a/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope/GoPackage.unit.json
+++ b/testdata/expected/program/go-misc/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["scope/scope.go"],"Dir":"scope","Dependencies":["fmt","strings"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"scope","Doc":"This package tests Exported and Local.","GoFiles":["scope.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope","ImportPos":null,"Imports":["fmt","strings"],"MFiles":null,"Name":"scope","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope","Type":"GoPackage","Repo":"github.com/sgtest/go-misc","Files":["scope/scope.go"],"Dir":"scope","Dependencies":["fmt","strings"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"scope","Doc":"This package tests Exported and Local.","GoFiles":["scope.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-misc/scope","ImportPos":null,"Imports":["fmt","strings"],"MFiles":null,"Name":"scope","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/go-sample-0/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg/GoPackage.unit.json b/testdata/expected/program/go-sample-0/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg/GoPackage.unit.json
index 7f851c1..4158087 100644
--- a/testdata/expected/program/go-sample-0/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg/GoPackage.unit.json
+++ b/testdata/expected/program/go-sample-0/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/go-sample-0","Files":["mypkg/bar.go","mypkg/foo.go"],"Dir":"mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"mypkg","Doc":"","GoFiles":["bar.go","foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg","ImportPos":null,"Imports":null,"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/go-sample-0","Files":["mypkg/bar.go","mypkg/foo.go"],"Dir":"mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"mypkg","Doc":"","GoFiles":["bar.go","foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-sample-0/mypkg","ImportPos":null,"Imports":[],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/go-testonly/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly/GoPackage.unit.json b/testdata/expected/program/go-testonly/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly/GoPackage.unit.json
index 8c8c597..f507d42 100644
--- a/testdata/expected/program/go-testonly/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly/GoPackage.unit.json
+++ b/testdata/expected/program/go-testonly/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly","Type":"GoPackage","Repo":"github.com/sgtest/go-testonly","Files":["foo_test.go"],"Dir":".","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":null,"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly","ImportPos":null,"Imports":null,"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["foo_test.go"],"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly","Type":"GoPackage","Repo":"github.com/sgtest/go-testonly","Files":["foo_test.go"],"Dir":".","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":null,"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go-testonly","ImportPos":null,"Imports":[],"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["foo_test.go"],"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/go13-sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample/GoPackage.unit.json b/testdata/expected/program/go13-sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample/GoPackage.unit.json
index 13c28a3..8765af2 100644
--- a/testdata/expected/program/go13-sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample/GoPackage.unit.json
+++ b/testdata/expected/program/go13-sample/sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample","Type":"GoPackage","Repo":"github.com/sgtest/go13-sample","Files":["go13sample.go"],"Dir":".","Dependencies":["fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["go13sample.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample","ImportPos":null,"Imports":["fmt"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOVERSION":"1.3"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample","Type":"GoPackage","Repo":"github.com/sgtest/go13-sample","Files":["go13sample.go"],"Dir":".","Dependencies":["fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"","GoFiles":["go13sample.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/go13-sample","ImportPos":null,"Imports":["fmt"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOVERSION":"1.3"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json b/testdata/expected/program/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json
index 55a5950..2e91015 100644
--- a/testdata/expected/program/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json
+++ b/testdata/expected/program/gopath-in-repo/mycompany.example.com/foo/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"mycompany.example.com/foo","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/foo/foo.go"],"Dir":"go/src/mycompany.example.com/foo","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/foo","Doc":"","GoFiles":["foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/foo","ImportPos":null,"Imports":null,"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"mycompany.example.com/foo","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/foo/foo.go"],"Dir":"go/src/mycompany.example.com/foo","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/foo","Doc":"","GoFiles":["foo.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/foo","ImportPos":null,"Imports":[],"MFiles":null,"Name":"foo","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json b/testdata/expected/program/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json
index ba00391..145c2cd 100644
--- a/testdata/expected/program/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json
+++ b/testdata/expected/program/gopath-in-repo/mycompany.example.com/mypkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"mycompany.example.com/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/mypkg/mypkg.go"],"Dir":"go/src/mycompany.example.com/mypkg","Dependencies":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/mypkg","Doc":"","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/mypkg","ImportPos":null,"Imports":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"mycompany.example.com/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/mycompany.example.com/mypkg/mypkg.go"],"Dir":"go/src/mycompany.example.com/mypkg","Dependencies":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/mycompany.example.com/mypkg","Doc":"","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"mycompany.example.com/mypkg","ImportPos":null,"Imports":["mycompany.example.com/foo","othercompany.example.com/otherpkg"],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json b/testdata/expected/program/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json
index 241539f..5d80389 100644
--- a/testdata/expected/program/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json
+++ b/testdata/expected/program/gopath-in-repo/othercompany.example.com/otherpkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"othercompany.example.com/otherpkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/othercompany.example.com/otherpkg/otherpkg.go"],"Dir":"go/src/othercompany.example.com/otherpkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/othercompany.example.com/otherpkg","Doc":"","GoFiles":["otherpkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"othercompany.example.com/otherpkg","ImportPos":null,"Imports":null,"MFiles":null,"Name":"otherpkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"othercompany.example.com/otherpkg","Type":"GoPackage","Repo":"github.com/sgtest/gopath-in-repo","Files":["go/src/othercompany.example.com/otherpkg/otherpkg.go"],"Dir":"go/src/othercompany.example.com/otherpkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"go/src/othercompany.example.com/otherpkg","Doc":"","GoFiles":["otherpkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"othercompany.example.com/otherpkg","ImportPos":null,"Imports":[],"MFiles":null,"Name":"otherpkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"go"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/gopathtest/github.com/alice/mypkg/GoPackage.unit.json b/testdata/expected/program/gopathtest/github.com/alice/mypkg/GoPackage.unit.json
index 1ddd9a2..b77ff46 100644
--- a/testdata/expected/program/gopathtest/github.com/alice/mypkg/GoPackage.unit.json
+++ b/testdata/expected/program/gopathtest/github.com/alice/mypkg/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/alice/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg/mypkg.go"],"Dir":"vendor/src/github.com/alice/mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg","Doc":"Package mypkg is a vendored dependency.","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg","ImportPos":null,"Imports":null,"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/alice/mypkg","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg/mypkg.go"],"Dir":"vendor/src/github.com/alice/mypkg","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg","Doc":"Package mypkg is a vendored dependency.","GoFiles":["mypkg.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg","ImportPos":null,"Imports":[],"MFiles":null,"Name":"mypkg","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json b/testdata/expected/program/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json
index 0719eb6..67fb0d0 100644
--- a/testdata/expected/program/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json
+++ b/testdata/expected/program/gopathtest/github.com/alice/mypkg2/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"github.com/alice/mypkg2","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg2/mypkg2.go"],"Dir":"vendor/src/github.com/alice/mypkg2","Dependencies":["github.com/alice/mypkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg2","Doc":"Package mypkg2 tests that it can import a vendored dep.","GoFiles":["mypkg2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg2","ImportPos":null,"Imports":["github.com/alice/mypkg"],"MFiles":null,"Name":"mypkg2","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"github.com/alice/mypkg2","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["vendor/src/github.com/alice/mypkg2/mypkg2.go"],"Dir":"vendor/src/github.com/alice/mypkg2","Dependencies":["github.com/alice/mypkg"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"vendor/src/github.com/alice/mypkg2","Doc":"Package mypkg2 tests that it can import a vendored dep.","GoFiles":["mypkg2.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"github.com/alice/mypkg2","ImportPos":null,"Imports":["github.com/alice/mypkg"],"MFiles":null,"Name":"mypkg2","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/gopathtest/sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest/GoPackage.unit.json b/testdata/expected/program/gopathtest/sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest/GoPackage.unit.json
index c425b08..704e8b7 100644
--- a/testdata/expected/program/gopathtest/sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest/GoPackage.unit.json
+++ b/testdata/expected/program/gopathtest/sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["gopathtest.go"],"Dir":".","Dependencies":["github.com/alice/mypkg","github.com/alice/mypkg2"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"Package gopathtest tests that it can access vendored deps in vendor/.","GoFiles":["gopathtest.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest","ImportPos":null,"Imports":["github.com/alice/mypkg","github.com/alice/mypkg2"],"MFiles":null,"Name":"gopathtest","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest","Type":"GoPackage","Repo":"github.com/sgtest/gopathtest","Files":["gopathtest.go"],"Dir":".","Dependencies":["github.com/alice/mypkg","github.com/alice/mypkg2"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":".","Doc":"Package gopathtest tests that it can access vendored deps in vendor/.","GoFiles":["gopathtest.go"],"Goroot":false,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"sourcegraph.com/sourcegraph/srclib-go/testdata/case/gopathtest","ImportPos":null,"Imports":["github.com/alice/mypkg","github.com/alice/mypkg2"],"MFiles":null,"Name":"gopathtest","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOPATH":"vendor"},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/minimal-go-stdlib/cmd/go/GoPackage.unit.json b/testdata/expected/program/minimal-go-stdlib/cmd/go/GoPackage.unit.json
index 058927b..94feb2a 100644
--- a/testdata/expected/program/minimal-go-stdlib/cmd/go/GoPackage.unit.json
+++ b/testdata/expected/program/minimal-go-stdlib/cmd/go/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"cmd/go","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/cmd/go/main.go"],"Dir":"src/cmd/go","Dependencies":["dummy0"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/cmd/go","Doc":"","GoFiles":["main.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"cmd/go","ImportPos":null,"Imports":["dummy0"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"cmd/go","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/cmd/go/main.go"],"Dir":"src/cmd/go","Dependencies":["dummy0"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/cmd/go","Doc":"","GoFiles":["main.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"cmd/go","ImportPos":null,"Imports":["dummy0"],"MFiles":null,"Name":"main","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/minimal-go-stdlib/dummy0/GoPackage.unit.json b/testdata/expected/program/minimal-go-stdlib/dummy0/GoPackage.unit.json
index 68bb3ca..0c6d8b4 100644
--- a/testdata/expected/program/minimal-go-stdlib/dummy0/GoPackage.unit.json
+++ b/testdata/expected/program/minimal-go-stdlib/dummy0/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"dummy0","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy0/dummy0.go","src/dummy0/dummy0_test.go"],"Dir":"src/dummy0","Dependencies":["dummy1","fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy0","Doc":"","GoFiles":["dummy0.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy0","ImportPos":null,"Imports":["dummy1","fmt"],"MFiles":null,"Name":"dummy0","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["dummy0_test.go"],"TestImportPos":null,"TestImports":["dummy1"],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"dummy0","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy0/dummy0.go","src/dummy0/dummy0_test.go"],"Dir":"src/dummy0","Dependencies":["dummy1","fmt"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy0","Doc":"","GoFiles":["dummy0.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy0","ImportPos":null,"Imports":["dummy1","fmt"],"MFiles":null,"Name":"dummy0","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":["dummy0_test.go"],"TestImportPos":null,"TestImports":["dummy1"],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/minimal-go-stdlib/dummy1/GoPackage.unit.json b/testdata/expected/program/minimal-go-stdlib/dummy1/GoPackage.unit.json
index b8a4013..5c3e949 100644
--- a/testdata/expected/program/minimal-go-stdlib/dummy1/GoPackage.unit.json
+++ b/testdata/expected/program/minimal-go-stdlib/dummy1/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"dummy1","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy1/dummy1.go","src/dummy1/dummy1_x_test.go"],"Dir":"src/dummy1","Dependencies":["dummy1"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy1","Doc":"","GoFiles":["dummy1.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy1","ImportPos":null,"Imports":null,"MFiles":null,"Name":"dummy1","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":["dummy1_x_test.go"],"XTestImportPos":null,"XTestImports":["dummy1"]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"dummy1","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/dummy1/dummy1.go","src/dummy1/dummy1_x_test.go"],"Dir":"src/dummy1","Dependencies":["dummy1"],"Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/dummy1","Doc":"","GoFiles":["dummy1.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"dummy1","ImportPos":null,"Imports":[],"MFiles":null,"Name":"dummy1","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":["dummy1_x_test.go"],"XTestImportPos":null,"XTestImports":["dummy1"]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/minimal-go-stdlib/fmt/GoPackage.unit.json b/testdata/expected/program/minimal-go-stdlib/fmt/GoPackage.unit.json
index 44838ee..ffc3f48 100644
--- a/testdata/expected/program/minimal-go-stdlib/fmt/GoPackage.unit.json
+++ b/testdata/expected/program/minimal-go-stdlib/fmt/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"fmt","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/fmt/fake_fmt.go"],"Dir":"src/fmt","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/fmt","Doc":"","GoFiles":["fake_fmt.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"fmt","ImportPos":null,"Imports":null,"MFiles":null,"Name":"fmt","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"fmt","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/fmt/fake_fmt.go"],"Dir":"src/fmt","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/fmt","Doc":"","GoFiles":["fake_fmt.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"fmt","ImportPos":null,"Imports":[],"MFiles":null,"Name":"fmt","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
diff --git a/testdata/expected/program/minimal-go-stdlib/runtime/GoPackage.unit.json b/testdata/expected/program/minimal-go-stdlib/runtime/GoPackage.unit.json
index 1212743..aee62a7 100644
--- a/testdata/expected/program/minimal-go-stdlib/runtime/GoPackage.unit.json
+++ b/testdata/expected/program/minimal-go-stdlib/runtime/GoPackage.unit.json
@@ -1 +1 @@
-{"Name":"runtime","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/runtime/runtime.go"],"Dir":"src/runtime","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/runtime","Doc":"","GoFiles":["runtime.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"runtime","ImportPos":null,"Imports":null,"MFiles":null,"Name":"runtime","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":null,"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":null},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
+{"Name":"runtime","Type":"GoPackage","Repo":"github.com/sgtest/minimal-go-stdlib","Files":["src/runtime/runtime.go"],"Dir":"src/runtime","Data":{"AllTags":null,"BinDir":"","CFiles":null,"CXXFiles":null,"CgoCFLAGS":null,"CgoCPPFLAGS":null,"CgoCXXFLAGS":null,"CgoFiles":null,"CgoLDFLAGS":null,"CgoPkgConfig":null,"ConflictDir":"","Dir":"src/runtime","Doc":"","GoFiles":["runtime.go"],"Goroot":true,"HFiles":null,"IgnoredGoFiles":null,"ImportComment":"","ImportPath":"runtime","ImportPos":null,"Imports":[],"MFiles":null,"Name":"runtime","PkgObj":"","PkgRoot":"","Root":"","SFiles":null,"SrcRoot":"","SwigCXXFiles":null,"SwigFiles":null,"SysoFiles":null,"TestGoFiles":null,"TestImportPos":null,"TestImports":[],"XTestGoFiles":null,"XTestImportPos":null,"XTestImports":[]},"Config":{"GOROOT":".","SourceImports":true},"Ops":{"depresolve":null,"graph":null}}
`
