// generated by stringer -type=PacketType; DO NOT EDIT

package main

import "fmt"

const (
	_PacketType_name_0 = "JoinServerRequestPacketTypeJoinServerAcceptPacketType"
	_PacketType_name_1 = "LocalPlayerInfoPacketType"
	_PacketType_name_2 = "HandshakePacketType"
)

var (
	_PacketType_index_0 = [...]uint8{0, 27, 53}
	_PacketType_index_1 = [...]uint8{0, 25}
	_PacketType_index_2 = [...]uint8{0, 19}
)

func (i PacketType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _PacketType_name_0[_PacketType_index_0[i]:_PacketType_index_0[i+1]]
	case i == 30:
		return _PacketType_name_1
	case i == 100:
		return _PacketType_name_2
	default:
		return fmt.Sprintf("PacketType(%d)", i)
	}
}
