// generated by gostringer -type=Pill; DO NOT EDIT

package painkiller

import "fmt"

const _Pill_name_gostringer = "PlaceboAspirinIbuprofenParacetamol"

var _Pill_index_gostringer = [...]uint8{0, 7, 14, 23, 34}

func (i Pill) GoString() string {
	if i < 0 || i+1 >= Pill(len(_Pill_index_gostringer)) {
		return fmt.Sprintf("painkiller.Pill(%d)", i)
	}
	return "painkiller." + _Pill_name_gostringer[_Pill_index_gostringer[i]:_Pill_index_gostringer[i+1]]
}
